contourpy/contourpy

.github/workflows/learn-github-actions.yml

Try out github actions

---

README.md
lib/contourpy/__init__.py
lib/contourpy/util/mpl_renderer.py
setup.py
src/chunk_local.cpp
src/chunk_local.h
src/mpl2014.cpp
src/outer_or_hole.cpp
src/outer_or_hole.h
src/serial.cpp
src/serial.h
src/wrap.cpp
tests/test_config.py
tests/test_filled.py
tests/test_lines.py
tests/util_test.py

Start of new serial contouring algorithm.  Only calculates filled contours so far, without a corner mask.
Chunks are implemented but not fully tested, e.g. boundary start points.
Performance exceeds both previous algorithms.

Start of new serial algorithm.

---

lib/contourpy/util/__init__.py
lib/contourpy/util/bokeh_renderer.py
lib/contourpy/util/mpl_renderer.py
requirements/examples.txt
src/serial.cpp

Added Bokeh renderer.  Also minor improvements to Matplotlib renderer.

Add bokeh renderer

---

.github/workflows/test.yml
requirements/test.txt

Add python 3.9 to CI

---

benchmarks/benchmarks/bench_fill_type.py
benchmarks/benchmarks/bench_fill_type_render.py
benchmarks/benchmarks/bench_filled.py
benchmarks/benchmarks/bench_filled_chunk.py
benchmarks/benchmarks/bench_filled_threaded.py
benchmarks/benchmarks/bench_line_type.py
benchmarks/benchmarks/bench_line_type_render.py
benchmarks/benchmarks/bench_lines.py
benchmarks/benchmarks/bench_lines_chunk.py
benchmarks/benchmarks/bench_lines_threaded.py
benchmarks/benchmarks/util_bench.py
lib/contourpy/__init__.py
lib/contourpy/mpl2005.py
lib/contourpy/util/bokeh_renderer.py
lib/contourpy/util/bokeh_util.py
lib/contourpy/util/chunk.py
lib/contourpy/util/mpl_renderer.py
lib/contourpy/util/mpl_util.py
setup.py
tests/image_comparison.py
tests/test_codebase.py
tests/test_config.py
tests/test_constructors.py
tests/test_enums.py
tests/test_filled.py
tests/test_interp.py
tests/test_lines.py
tests/test_static.py
tests/util_config.py
tests/util_test.py

Standardise on double quotes for python strings

Standardise on double quotes for python strings

---

benchmarks/benchmarks/bench_fill_type_render.py
benchmarks/benchmarks/bench_line_type_render.py

More benchmark fixes

---

src/base.h
src/base_impl.h
src/serial.cpp
src/threaded.cpp

Combine `BaseContourGenerator`  `march_chunk_filled()` and `march_chunk_lines()` into `march_chunks()` to reduce code duplication.

Combine march functions

---

.github/workflows/build_wheels.yml

Add building of sdist as well as binary wheels in github action `build_wheels.yml`.

Build sdist along with bdist wheels

---

.github/workflows/build_wheels.yml
setup.cfg

Include license file in sdist.

Include license file in sdist

---

.github/workflows/build_wheels.yml
.github/workflows/test.yml
setup.cfg

Add Python 3.10 to CI, both tests and build_wheels.

Add python 3.10 to tests and build_wheels

---

LICENSE
docs/conf.py

Update copyright date to 2022.

Update copyright date to 2022

---

lib/contourpy/__init__.py
tests/test_constructor.py
tests/test_filled.py
tests/test_lines.py
tests/test_z_interp.py

Be explicit about what are `args` and what are `kwargs` to `contour_generator`.

contour_generator args vs kwargs

---

.readthedocs.yaml
docs/conf.py
setup.cfg

Add readthedocs yaml config file

---

.github/CODE_OF_CONDUCT.md
.github/SECURITY.md
README.md
benchmarks/README.md
benchmarks/benchmarks/bench_filled_threaded.py
benchmarks/benchmarks/bench_lines_threaded.py
docs/index.rst
setup.cfg

Documentation updates:
* Updated main README
* Added benchmarking README
* Added security policy
* Added code of conduct
* Update classifiers
* Enabled flake8 on docs and benchmarks, and added a couple of fixes

Updated readmes, added security policy, code of conduct

---

MANIFEST.in

Add docs and tests to sdist

---

docs/user_guide/fill_type.rst
lib/contourpy/__init__.py

Doc updates

---

.github/workflows/build_wheels.yml

Update cibuildwheel to 2.8.1 and macOS GHA runner.

Update cibuildwheel to 2.8.1

---

tests/test_codebase.py

Avoid spurious `assertWithSideEffect` error that occurs with `cppcheck` 2.7.1.

Avoid spurious error with cppcheck 2.7.1

---

tests/test_constructor.py

Add more tests to `test_constructor.py`, particularly to check raised exceptions.

Add more constructor tests

---

docs/conf.py
pyproject.toml

Use sphinx copy button in docs.

Use sphinx copy button

---

.gitignore
docs/sphinxext/name_supports.py
docs/sphinxext/name_supports_type.py
docs/sphinxext/plot_directive.py
docs/sphinxext/table.py
pyproject.toml

Add type annotations to `docs` directory. There are a lot of `Any`s here, but at least it is in line with the rest of this project.

Add type annotations to docs directory

---

.cirrus.yml

Trying out cirrus CI for building and testing on aaarch64.

Try building and testing on cirrus CI

---

.pre-commit-config.yaml
pyproject.toml
tests/util_test.py

Update pre-commit hooks

---

.pre-commit-config.yaml
pyproject.toml

Update version of `ruff` used in `pre-commit` to `0.0.253`.

Update ruff to 0.0.253

---

lib/contourpy/util/__init__.py
lib/contourpy/util/_build_config.pyi
pyproject.toml
tests/test_renderer.py

Upgrade mypy to 1.2.0

---

.github/codecov.yml
.github/workflows/test.yml

Some improvements to CI (github actions):
- Separate `codebase` run that uses `mypy` and `cppcheck`, so these can both be removed from other CI runs.
- Remove Bokeh tests from C++ coverage run.
- New run with Bokeh and text tests, for Python coverage.
- Separate C++11 run.

Ci improvements

---

.github/codecov.yml
.pre-commit-config.yaml
benchmarks/plot_benchmarks.py
docs/conf.py
docs/sphinxext/name_supports.py
docs/sphinxext/name_supports_type.py
docs/sphinxext/plot_directive.py
lib/contourpy/util/mpl_renderer.py
pyproject.toml
tests/test_build_config.py
tests/test_codebase.py
tests/test_constructor.py
tests/test_filled.py
tests/test_lines.py
tests/util_config.py

Update ruff to v0.0.267 and add a few more rules.

Update ruff to v0.0.267

---

.pre-commit-config.yaml
docs/benchmarks/threads.rst
docs/sphinxext/name_supports.py
docs/sphinxext/plot_directive.py
pyproject.toml

Update pre-commit and mypy:
- mypy 1.4.1
- ruff 0.0.275
- validate-pyproject 0.13
- add codespell 2.2.4 and pyupgrade 3.7.0
Codespell found one typo.

Update pre-commit and mypy

---

lib/contourpy/_contourpy.pyi

https://github.com/contourpy/contourpy/blob/main/src/wrap.cpp#L34

Sync constant name with C++ code

---

lib/contourpy/chunk.py
tests/test_chunk.py

This adds improved validation of the internal functions in `chunk.py` and new tests of these functions.

Improved validation in internal chunk functions

---

tests/test_bokeh_renderer.py
tests/test_renderer.py

Add tests for saving to PNG and SVG files using Matplotlib and Bokeh renderers.
Using Bokeh to save to PNG with a transparent background isn't working as expected whereas to SVG it is. I think this is a Bokeh rather than ContourPy issue but it needs further investigation.

Add tests for saving to PNG and SVG using Matplotlib and Bokeh renderers

---

.github/workflows/build_wheels.yml
pyproject.toml

Reinstate building of Windows 32-bit wheels.
They will be included in the impending 1.1.1rc1 release candidate.

Reinstate building of Windows 32-bit wheels

---

docs/api/top.rst
lib/contourpy/__init__.py
lib/contourpy/convert.py
lib/contourpy/dechunk.py
lib/contourpy/meson.build
lib/contourpy/types.py
tests/test_convert.py
tests/util_test.py

Add a new function `convert_line_type` which is used to convert contour lines from one `LineType` to another.

Add new function convert_line_type

---

docs/user_guide/fill_type.rst
lib/contourpy/__init__.py
lib/contourpy/convert.py
tests/test_convert.py
tests/test_dechunk.py
tests/util_test.py

Add a new function `convert_fill_type` which is used to convert contour lines from one `LineType` to another. Companion function to `convert_line_type` (#291).

Add new function convert_fill_type

---

benchmarks/plot_benchmarks.py

Extract benchmark ratios when generating benchmark plots. This makes it easier to update the numbers in the docs when rerunning the benchmarks, as must be done shortly for the new `LineType.ChunkCombinedNan`.

Extract benchmark ratios when generating benchmark plots

---

.github/workflows/test.yml
benchmarks/plot_benchmarks.py
lib/contourpy/util/mpl_renderer.py
tests/util_config.py

Update type annotations for matplotlib 3.8. Fixes #277.

Update type annotations for matplotlib 3.8

---

pyproject.toml

Add a few more lines to the list of those excluded from coverage reports.

More coverage excludes

---

.pre-commit-config.yaml
docs/sphinxext/table.py
lib/contourpy/array.py
lib/contourpy/enum_util.py
lib/contourpy/util/mpl_renderer.py
pyproject.toml
tests/conftest.py
tests/test_bokeh_renderer.py
tests/test_chunk.py
tests/util_config.py

Update versions of `pre-commit`, `ruff` and `mypy`, and add a few more `ruff` rules with corresponding code changes, all uncontroversial.

Update pre-commit, ruff and mypy

---

.cirrus.yml
.github/workflows/test.yml
docs/developer_guide.rst
pyproject.toml

Run test suite in parallel for better use of multiple CPUs in CI.

Run test suite in parallel

---

.github/workflows/test.yml
src/mpl2014.cpp
tests/test_codebase.py

Update cppcheck to 2.11

---

benchmarks/loader.py
benchmarks/plot_benchmarks.py
tests/util_config.py

Fix a few strings that should have been f-strings but weren't. They are only in benchmark and test code.

Fix a few f-strings

---

.pre-commit-config.yaml
benchmarks/benchmarks/bench_filled_threaded.py
benchmarks/benchmarks/bench_lines_threaded.py
lib/contourpy/__init__.py
lib/contourpy/dechunk.py
lib/contourpy/util/bokeh_util.py
pyproject.toml
tests/test_convert.py
tests/test_internal.py
tests/test_static.py
tests/test_typecheck.py
tests/util_config.py

Use ruff's isort instead of standalone isort in pre-commit.

Use ruff's isort

---

.cirrus.yml

Store artifacts of CirrusCI runs containing test image differences.

Store CirrusCI artifacts

---

.pre-commit-config.yaml
pyproject.toml

Update ruff to 0.1.9 and mypy to 1.8.0.

Update ruff to 0.1.9 and mypy to 1.8.0

---

LICENSE
docs/conf.py

Update copyright date to 2024.

Update copyright date to 2024

---

.github/workflows/build_wheels.yml
.github/workflows/test.yml

Bump github actions

---

lib/contourpy/_version.py
meson.build

Bump version to 1.3.0.dev1

---

.github/workflows/test.yml
src/base.h
src/base_impl.h
src/converter.cpp

Update cppcheck to 2.13.0

---

lib/contourpy/util/renderer.py
pyproject.toml

Some improvements to `pyproject.toml` in line with https://github.com/scientific-python/repo-review. More to follow.

Some pyproject.toml improvements

---

.github/dependabot.yml

Add `dependabot.yml` for auto version updates in github actions.

Add dependabot.yml for auto version updates in gha

---

.github/workflows/test.yml

Add CI coverage for the 3.13 free-threaded build of CPython

---

build_requirements.txt
pyproject.toml
src/wrap.cpp

Related to #407.
It'd probably be best to merge #408 first, so that this gets CI coverage on the free-threaded build.

Add mod_gil_not_used call to PYBIND11_MODULE

---

lib/contourpy/array.py
pyproject.toml
tests/util_config.py

Update mypy to 1.11.1 and remove some unnecessary `type: ignore` comments.

Update mypy to 1.11.1

---

tests/util_test.py

Changes to support improved typing in numpy 2.1.0.

Changes to support improved typing in numpy 2.1.0

---

LICENSE
docs/conf.py

Update copyright date to 2025.

Update copyright date to 2025

---

benchmarks/benchmarks/bench_base.py
benchmarks/plot_benchmarks.py
lib/contourpy/util/mpl_renderer.py
pyproject.toml
tests/test_lines.py
tests/util_config.py

Update `mypy` to 1.15.0, and make changes to support type changes in latest `numpy` 2.2.3.

Update mypy to 1.15.0

---

.github/workflows/test.yml

Test on CPython 3.14

---

lib/contourpy/util/bokeh_renderer.py

Update type annotations for bokeh 3.7.3.

Update type annotations for bokeh 3.7.3

---

.github/workflows/build_wheels.yml
.github/workflows/test.yml
.github/workflows/test_own_nightlies.yml

cf https://github.com/matplotlib/matplotlib/pull/28554#issuecomment-2946405561 this does appear to build fine already. Will have to see how tests go.

Build and test for Windows on ARM
