contourpy/contourpy

lib/contourpy/__init__.py
lib/contourpy/util/mpl_renderer.py
lib/contourpy/util/mpl_util.py
setup.py
src/common.h
src/fill_type.cpp
src/fill_type.h
src/mpl2014.cpp
src/serial.cpp
src/serial.h
src/wrap.cpp
tests/test_config.py
tests/test_enums.py
tests/test_filled.py
tests/util_test.py

Added FillType C++ enum for returned fill type, and wrapped this using pybind11 so can be used in Python.
Implemented 6 different fill types: using mpl codes or offsets, and either combined together (single numpy array of points per chunk) or combined via outer lines.

Add other return FillTypes to serial algorithm

---

lib/contourpy/__init__.py
lib/contourpy/util/mpl_renderer.py
setup.py
src/line_type.cpp
src/line_type.h
src/serial.cpp
src/serial.h
src/wrap.cpp
tests/test_enums.py
tests/test_lines.py
tests/util_test.py

Added `contour_lines` to serial algorithm (no corner mask).  Performance is better than mpl2005 but not as good as mpl2014.  Only uses line_type of `Separate` so far.

Contour lines in serial algorithm, no corner mask

---

lib/contourpy/util/mpl_renderer.py
setup.py
src/converter.cpp
src/converter.h
src/fill_type.h
src/line_type.cpp
src/line_type.h
src/mpl2005.c
src/mpl2014.cpp
src/mpl2014.h
src/serial.cpp
src/serial.h
src/wrap.cpp
tests/test_filled.py
tests/test_lines.py
tests/util_config.py
tests/util_test.py

Added various `LineType`s to serial algorithm, and improved conversion functions from C++ to Python objects.
Also modified return of mpl2005 and mpl2014 algorithms to be a tuple of a single list, in preparation for chunking.

Add different return LineTypes to serial algorithm

---

README.md
setup.py

Using pybind11's `ParallelCompile` and `naive_recompile` to build in parallel and only build source code files that have changed (but ignoring header file changes).
Also using `setuptools.find_packages` to correctly find directories to install so that building works in place or not.

Improved build options

---

lib/contourpy/__init__.py
lib/contourpy/util/bokeh_renderer.py
lib/contourpy/util/mpl_renderer.py
src/serial.cpp
src/serial_corner.cpp
tests/test_constructors.py

In `contour_generator`, `x` and `y` can now be
- 2D arrays of shape `(ny, nx)`.
- 1D arrays of shape `(nx,)` and `(ny,)` respectively.
- `None`, in which case `np.arange(nx)` and `np.arange(ny)` are used.
C/C++ code still expects 2D arrays for both.

Accept x and y as 0D and 1D arrays in Python wrapper

---

lib/contourpy/__init__.py
setup.py
src/interp.cpp
src/interp.h
src/serial.cpp
src/serial.h
src/serial_corner.cpp
src/serial_corner.h
src/wrap.cpp
tests/test_enums.py
tests/test_filled.py
tests/test_interp.py
tests/test_lines.py
tests/util_test.py

Adds logarithmic interpolator to new algorithms, to complement default linear interpolator.
Temporarily disabled chunk tests because of issue #19.

Add logarithmic interpolator

---

src/serial.cpp
src/serial_corner.cpp
tests/test_filled.py
tests/test_lines.py

Access violation when using chunking on windows (issue #19) due to reading memory before the beginning of `_cache` in `init_cache_levels_and_starts`.  Value read was never used.  Didn't report any access violations on linux or macos.

Fix bug when chunking on windows

---

lib/contourpy/__init__.py
setup.py
src/threaded.cpp
src/threaded.h
src/wrap.cpp
tests/test_config.py
tests/test_constructors.py
tests/test_interp.py
tests/util_test.py

Start of multithreaded algorithm under the name `threaded`.  Threads are created within each call to `lines()` or `filled()` and are only used in the `march()` function.  Locking using `mutex`es is locking for longer than is strictly necessary.  This PR is primarily to check that the code builds and runs on Windows and MacOS.

Multithreaded algorithm, march() function only

---

src/threaded.cpp
src/threaded.h

This PR extends the `threaded` algorithm to multithread the `init_cache_levels_and_starts` as well as the contour tracing.
Multithreading occurs in a single `thread_function` call (per thread, per call to `filled` or `lines`). As before, processing is on a per-chunk basis.  A thread in need of work takes the next available `chunk` and processes it.  The first stage (init cache levels and starts) completes before the second stage (contour trace) starts so that the cache is fully initialised before any chunk uses it.  There is a multithreaded barrier between the two stages, implemented using a `condition_variable` and counter to keep the code conformant to C++11.
Performance improvement looks promising, but need repeatable benchmarking code to investigate/demonstrate this properly.

Multithreaded the init cache levels and starts

---

lib/contourpy/__init__.py
setup.py
src/common.h
src/threaded.cpp
src/threaded.h
src/util.cpp
src/util.h
src/wrap.cpp
tests/test_constructors.py

Moved C++ `get_max_threads()` out of threaded algorithm and into separate file.  This can now be accessed from python using
```python
contourpy.max_threads()
```
without/before having to create a `ThreadedContourGenerator`.

Separate contourpy.max_threads() function

---

.github/workflows/test.yml

If there are any image test failures during Github Actions runs, an artifact is created and uploaded.

Upload failed image tests to GHA artifact file

---

lib/contourpy/__init__.py
lib/contourpy/mpl2005.py
lib/contourpy/util/chunk.py
setup.py
src/mpl2005.c
src/mpl2014.cpp
src/mpl2014.h
src/wrap.cpp
tests/test_constructors.py
tests/test_filled.py
tests/test_lines.py
tests/test_static.py
tests/util_test.py

Added various `default_` and `supports_` functions/properties to `mpl2005` and `mpl2014`.
Wrapped `mpl2005` C extension with a Python wrapper so that don't have to make C extension aware of C++ enums like `FillType`.  Removed some unused code in C extension.
Improved `contour_generator` in `__init__.py` to check validity of arguments and their default values using the classes themselves rather than being hard-coded.

Add full set of properties and static functions to mpl2005 and mpl2014

---

lib/contourpy/util/bokeh_renderer.py
lib/contourpy/util/bokeh_util.py
lib/contourpy/util/mpl_renderer.py
lib/contourpy/util/mpl_util.py
tests/test_filled.py
tests/test_lines.py

Improvements to Matplotlib and Bokeh renderers:
- Removed grid `x, y` from `Renderer` constructors.
- Created Matplotlib utility functions: `filled_to_mpl_paths` and `lines_to_mpl_paths`.
- Created Bokeh utility functions: `filled_to_bokeh` and `lines_to_bokeh`.

Renderer improvements

---

lib/contourpy/__init__.py
lib/contourpy/mpl2005.py
src/mpl2014.cpp
src/mpl2014.h
src/serial.cpp
src/threaded.cpp
src/wrap.cpp
tests/test_static.py

`contour_generator` creates `ContourGenerator` objects using `args` and `kwargs`.  `line_type` and `fill_type` are now keyword args to all contour generators.

Create contour generators using args and kwargs

---

src/common.h
src/converter.cpp
src/converter.h
tests/test_filled.py
tests/test_lines.py

Change the `dtype` of offset numpy arrays returned to python to be `npy_intp`.  This will be `int64_t` on 64-bit systems and `int32_t` on 32-bit systems.  This ensures that the offset values can indeed be used as offsets within the `points` and other arrays.
Internally the offsets are stored as unsigned integers as they are determined from the lengths/offsets of `std::vector`s.  Hence also added code that throws an exception if an offset will exceed the signed limit.

Change returned offset arrays to have dtype of npy_intp

---

benchmarks/benchmarks/bench_fill_type.py
benchmarks/benchmarks/bench_fill_type_render.py
benchmarks/benchmarks/bench_filled.py
benchmarks/benchmarks/bench_filled_chunk.py
benchmarks/benchmarks/bench_filled_threaded.py
benchmarks/benchmarks/bench_line_type.py
benchmarks/benchmarks/bench_line_type_render.py
benchmarks/benchmarks/bench_lines.py
benchmarks/benchmarks/bench_lines_chunk.py
benchmarks/benchmarks/bench_lines_threaded.py
benchmarks/benchmarks/util_bench.py
lib/contourpy/__init__.py
lib/contourpy/util/bokeh_renderer.py
lib/contourpy/util/bokeh_util.py
lib/contourpy/util/chunk.py
lib/contourpy/util/mpl_renderer.py
lib/contourpy/util/mpl_util.py
requirements/test.txt
setup.cfg
setup.py
tests/image_comparison.py
tests/test_codebase.py
tests/test_constructors.py
tests/test_enums.py
tests/test_filled.py
tests/test_interp.py
tests/test_lines.py
tests/test_misc.py
tests/test_static.py
tests/util_config.py

This PR adds flake8 linting as part of pytest.  Python line length is increased to 120, and various linting errors fixed.

Add flake8 linting

---

src/base.h
src/base_impl.h

Don't need to create temporary `Location` objects to pass to `closed_contour_wrapper()` etc as such functions accept a constant reference and so the `Location` can be constructed directly within the function call.

Remove temporary Location objects

---

src/base.h
src/base_impl.h

Add two new `BaseContourGenerator` functions `get_boundary_start_point()` and `get_interior_start_left_point()`.  Previously these were code blocks at the start of `follow_boundary()` and `follow_interior()` respectively.

New functions get_boundary_start_point and get_interior_start_left_point

---

lib/contourpy/util/mpl_renderer.py
src/base.h
src/base_impl.h
src/chunk_local.cpp
src/chunk_local.h
src/common.h
src/converter.cpp
src/converter.h
tests/test_filled.py
tests/test_lines.py
tests/util_test.py

Added separate `count_t` and `offset_t` typedefs to `serial` and `threaded` algorithms.  `count_t` is used for count of points, lines and holes in `ChunkLocal`, and `offset_t` is used for offsets into point and line arrays.
`count_t` is the same as `py::size_t`  and `npy_uintp`, i.e. unsigned 64-bit on 64-bit machines.
`offset_t` is `uint32_t` on all platforms.  Maximum value is 2<sup>32</sup>-1 = 4,294,967,295.  Minimum chunk size to hit this limit for filled contours (assuming 2 contour points per quad) is 46340.  Corresponding points array would be ~64 GB in size.  It is reasonable to assume users will be using smaller chunks than this!
Note that this is partial reversion of issue #39.

Add count_t and offset_t types

---

src/base.h
src/base_impl.h
src/chunk_local.cpp
src/chunk_local.h
src/converter.cpp
src/output_array.h

Added new C++ class `OutputArray<T>` to combine the possibilities of outputting arrays directly to Python (NumPy) arrays or to C++ vectors first.  Marching functions don't care which it is, they just append to an incrementing pointer.  This is a cleaner solution to that previously.
Also change `interp()` to accept a `double*&` rather than `ChunkLocal&` so that the `OutputArray<T>`'s current pointer is passed straight in.

New OutputArray<T> class for combined chunk points

---

src/base.h
src/base_impl.h
src/chunk_local.cpp
src/chunk_local.h
src/converter.cpp
src/output_array.h

Output offset arrays direct to python where possible, using new `OutputArray<T>` class.
Whether to output directly to python or not is controlled by `BaseContourGenerator` member variables `_direct_points`, `_direct_line_offsets` and `_direct_outer_offsets`, which are set at the start of each call to `filled()` or `lines()`.
Also some minor replacement of C++ pointer dereferencing with array notation.

Use OutputArray<T> for line and outer offsets

---

src/base_impl.h

In `BaseContourGenerator.export_filled()` and `export_lines()`, moved use of threading `Lock` from outside `switch` statement to within those `case` statements that require it.  Hence there is no longer any locking where it is not required, i.e. for
`fill_type == FillType::ChunkCombinedOffsets` or `FillType::ChunkCombinedOffsets`
`line_type == LineType:: ChunkCombinedOffsets`

Finer-grain locking in export_filled/lines

---

src/base.h
src/base_impl.h
src/chunk_local.h
src/converter.cpp
src/converter.h

Clarified that `outer_offsets` can be indexed into either points or lines, depending on `FillType`.  Added a new member variable to `BaseContourGenerator` called `_outer_offsets_into_points`.  This is only `true` for fill type of `ChunkCombinedCodesOffsets`.  Functional change here is to write this directly to the NumPy outer offsets array rather than via an intermediate C++ vector indexed into line offsets.
`Converter::convert_offsets_nested` removed as no longer needed.

Add option to save outer_offsets into points not line_offsets

---

.github/workflows/test.yml
README.md
setup.py
src/wrap.cpp

Added environment variables to control some aspects of build process.  These are BUILD_DEBUG that builds in debug mode and in particular enables the `assert`s in the C++ code, and BUILD_CXX11 which forces use of c++11 standard rather than using the latest C++ standard available.  To build using both of these use
```
BUILD_DEBUG=1 BUILD_CXX11 pip install -ve .
```
Added attributes to the `_contourpy` extension so that the values used at build time are stored and can be checked later.
Also added a new CI test run with uses both of these flags.

Build environment variables

---

lib/contourpy/util/mpl_renderer.py
src/base_impl.h
tests/test_interp.py

Log interpolation has been implemented for interpolation of contour levels on grid cell edges, but not for calculation of the z-level in the centre of saddle quads.  This PR corrects that.
Test added.
Also add new `util` function `MplRenderer.z_values()` to display the z-values at grid points which will help with examples to explain what is occurring here.  Have not done this for `BokehRenderer` yet.

Implement log interpolation for saddle quads

---

.github/workflows/build_wheels.yml

`build_wheels` CI action should only run when pushing a tag, or on demand.

CI build wheels less often

---

src/base.h
src/base_impl.h

Store `double*` pointers to `data()` of x, y, z arrays in constructor of `BaseContourGenerator` rather than repeatably calling `data()` in the various functions like `get_point_x()`.  Improves performance, particularly for complicated contour calculations.

Use x, y, z pointers for quicker access to numpy arrays

---

tests/image_comparison.py
tests/test_filled.py

On 32-bit, Matplotlib agg backend produces RGB components that are sometimes 1 out compared to 64-bit, so ignore test image differences of 1 on 32-bit.

32bit support

---

src/base.h
src/base_impl.h

Replace use of `int turn_left` with `Direction` enum in `BaseContourGenerator<>::follow_interior` as easier to understand and can use `switch` statements instead of multiple `if` statements.

Use enum for Direction in follow_interior

---

lib/contourpy/__init__.py
src/mpl2014.cpp
src/mpl2014.h
src/wrap.cpp

As `mpl2014` only supports a single `LineType` and `FillType`, here moving all `Line/FillType` handling up to `wrap.cpp` so that there is no dependency on `line_type.h` or `fill_type.h` in `Mpl2014ContourGenerator` class.

Move mpl2014 line and fill_type handling up to wrap.cpp

---

src/base.h
src/base_impl.h

This PR changes the logic used in `init_cache_levels_and_starts()` from `if` to `switch` statements using the numerical `config` of each quad in turn.  Saddle z-levels are also calculated here, rather than when first needed, using the `config` values.  Also reordered the 2 loops from (1) filled or not and (2) quad or corner to the other way around which speeds up the processing of masked quads.
This is a major change in the number of lines of code as it introduces repeated duplication of code to create the possible start flags.  It is justifiable on performance grounds as we only need to check for starts that are possible for each specific config.  Hence there is a reduction in the number of if-statements and also better grouping of the remaining checks, e.g. `start_in_row` doesn't need …

Use switch statement on config to determine possible starts

---

src/base.h
src/base_impl.h

In `BaseContourGenerator`, pass and return `double`s to and from functions instead of const references. Improves performance.

Pass doubles by value rather than const reference

---

src/base_impl.h

A few minor improvements to `BaseContourGenerator`:
* Reorder `#defines` more alphabetically.
* Improvments to `if` and `switch` statements.
* Reuse of `z_to_zlevel()` rather than duplicating code.

Minor improvments to BaseContourGenerator

---

src/base_impl.h

Don't need to set `START_HOLE_N` in any quad that is adjacent to a `BOUNDARY_W` or `BOUNDARY_E` as it won't be a real start. Didn't cause a problem, but good to avoid the unnecessary set and clear.

Improved setting of START_HOLE_N

---

.github/workflows/test.yml
README.md
setup.py
src/wrap.cpp

Rename environment variables BUILD_DEBUG and BUILD_CXX11 to CONTOURPY_BUILD and CONTOURPY_CXX11 instead, for increased clarity.

Rename BUILD_* to CONTOURPY_*

---

src/threaded.cpp

Fixes warning when building in 32-bit Linux docker container of incorrect type used for `for` loop involving `_n_threads`.

Remove 32-bit warning about different integer signedness

---

.github/workflows/build_wheels.yml
src/base_impl.h
src/serial.h
src/threaded.h

Improvement to assist with conda builds:
1. Verbose `cibuildwheel` action to identify errors and warnings.
2. More specific templated `friend` declarations.
3. Explicit conversion of `ANY_START(quad)` to `bool`.
Item 2 is the important one here, it was identified when trying to build packages on conda-forge that use an older MSVC compiler.

Improvements for conda build

---

src/base.h
src/base_impl.h
src/wrap.cpp
tests/test_constructors.py
tests/test_static.py

Add readonly properties to all contour generator classes so that they implement the same interface. Add tests for this too.

All ContourGenerator classes implement the same readonly properties

---

lib/contourpy/__init__.py
src/fill_type.cpp
src/fill_type.h
src/line_type.cpp
src/line_type.h
src/wrap.cpp
src/z_interp.cpp
src/z_interp.h
tests/test_constructors.py
tests/test_enums.py

Allows use of e.g. `contour_generator(..., line_type="SeparateCodes")` and similar for `fill_type` and `z_interp`.

Support string to enum conversion in contour_generator

---

.github/workflows/build_wheels.yml
pyproject.toml

It is recommended to build `sdist`s using
```
pip install build
python -m build --sdist
```
for full PEP517/518 compliance rather than the older `python setup.py sdist`.
Also support building of PyPy 3.7 packages.

Improved build system

---

src/base_impl.h
tests/test_static.py
tests/util_config.py

For `serial` and `threaded` algorithms, set default line type to be `LineType.Separate` and default fill type to `FillType.OuterOffsets`.

Default line/fill type for serial/threaded

---

lib/contourpy/__init__.py
lib/contourpy/enum_util.py
lib/contourpy/util/bokeh_renderer.py
lib/contourpy/util/mpl_renderer.py
lib/contourpy/util/mpl_util.py
setup.cfg
src/fill_type.cpp
src/fill_type.h
src/line_type.cpp
src/line_type.h
src/wrap.cpp
src/z_interp.cpp
src/z_interp.h
tests/test_codebase.py
tests/test_config.py
tests/test_constructor.py
tests/test_enum.py
tests/test_filled.py
tests/test_lines.py
tests/test_renderer.py
tests/test_static.py
tests/test_z_interp.py
tests/util_config.py
tests/util_test.py

Moved conversion of strings to enums from C++ to Python. Also improved order of some import statements.

String to enum moved from C++ to python

---

src/mpl2005.cpp
src/mpl2005.h

Do not need to store the `mask` in `Mpl2005ContourGenerator` as it is only used in the constructor.

Don't store mask in mpl2005

---

.github/workflows/build_wheels.yml
pyproject.toml

This adds building the full set of wheels to the `cibuildwheel` github action. Takes about 2 hours to run, artifact is 20 MB.
Linux: x86_64, i686 and aarch64 on manylinux and musllinux.
macOS: x86_64, arm64 and universal2.
Windows: win_amd64 and win32.
Not all for all versions of Python.

Build more wheels via cibuildwheels

---

lib/contourpy/util/mpl_renderer.py
src/base_impl.h
src/output_array.h
tests/test_filled.py
tests/test_lines.py
tests/util_test.py

Fixed a bug due to missing some possible corner starts for a SW corner.
- Added more asserts in `base_impl.h` to check for situations like this in future. 
- Improved testing framework for `lines` and `filled` according to their `line_type`/`fill_type`.
- Added big 1000x1000 filled and line tests.
- Added mask rendering function to `MplDebugRenderer`.

Fixed missing SW corner mask starts

---

benchmarks/benchmarks/bench_filled_mpl20xx.py
benchmarks/benchmarks/bench_filled_mpl20xx_render.py
benchmarks/benchmarks/bench_filled_serial_chunk.py
benchmarks/benchmarks/bench_filled_serial_quad_as_tri.py
benchmarks/benchmarks/bench_filled_serial_quad_as_tri_render.py
benchmarks/benchmarks/bench_filled_threaded.py
benchmarks/benchmarks/bench_lines_mpl20xx.py
benchmarks/benchmarks/bench_lines_mpl20xx_render.py
benchmarks/benchmarks/bench_lines_serial_chunk.py
benchmarks/benchmarks/bench_lines_serial_quad_as_tri.py
benchmarks/benchmarks/bench_lines_serial_quad_as_tri_render.py
benchmarks/benchmarks/bench_lines_threaded.py
docs/user_guide/fill_type.rst
docs/user_guide/line_type.rst
docs/user_guide/threads.rst
lib/contourpy/util/bokeh_util.py
lib/contourpy/util/mpl_renderer.py
lib/contourpy/util/mpl_util.py
src/base_impl.h
src/fill_type.cpp
src/fill_type.h
src/line_type.cpp
src/line_type.h
src/wrap.cpp
tests/test_constructor.py
tests/test_filled.py
tests/test_lines.py
tests/test_static.py
tests/util_config.py
tests/util_test.py

Finalise the enum spellings. Preferring singular to plural, and avoiding `Offset2` as there is also a valid `Offset` and the single character difference is dangerous.

Finalise enum spellings

---

docs/user_guide/z_corner_mask.rst
lib/contourpy/util/bokeh_renderer.py
lib/contourpy/util/mpl_renderer.py

Previously had a part-implemented `MplRenderer.mask` function to render masked out points as coloured circles. This PR completes that and the Bokeh equivalent, with docstrings, and updates the `corner_mask` example in the docs to use the mask to make the explanation clearer.

Complete mask render function

---

src/base.h
src/base_impl.h
tests/conftest.py
tests/test_filled.py

Added `test_filled_compare_slow` which is a 1000 times repeated slow test, to run through lots of random `corner_mask=True` data sets and compare the outputs (number of lines, outers and points) for `mpl2014` and `serial`. This test is not run by default as takes ~30 minutes on my 6-core dev laptop (using `pytest-xdist`).
Also changed asserts that line/outer/hole counts are the same after each pass into exceptions, as they usually indicate a bug in the `serial` code that need to be identified without running in debug mode.

Test filled compare slow

---

docs/api/top.rst
src/wrap.cpp
tests/test_static.py

Add synonym functions for backward compatibility with matplotlib:
* `create_contour` -> `lines`
* `create_filled_contour` -> `filled`

Synonym functions for backward compatibility with matplotlib

---

docs/user_guide/z_corner_mask.rst
lib/contourpy/__init__.py
tests/test_misc.py

As well as supporting `z` being a masked array, also convert `np.nan` and `np.inf` to mask too.

Convert np.nan/np.inf in z to masked array

---

setup.cfg

Relax min numpy version requirement from 1.20 to 1.16.

Relax numpy version requirement

---

setup.cfg

`license_file` is deprecated in setuptools, use `license_files` instead.

Rename license_file to license_files

---

docs/api/top.rst
docs/benchmarks/threads.rst
docs/quickstart.rst
docs/usage.rst
docs/user_guide/fill_type.rst
docs/user_guide/line_type.rst
docs/user_guide/x_and_y.rst
docs/user_guide/z_corner_mask.rst
lib/contourpy/__init__.py
lib/contourpy/util/bokeh_renderer.py
lib/contourpy/util/mpl_renderer.py
src/base.h
src/contour_generator.h
src/mpl2005.h
src/mpl2014.h
src/wrap.cpp
tests/test_constructor.py

This PR adds a `ContourGenerator` base class to all 4 contouring algorithms. The class is abstract so cannot be instantiated. On the C++ side it contains no methods, but in the `pybind11` wrapper it defines all the methods and properties that each of the 4 algorithms implements.
Benefits:
- Can use `isinstance(object, ContourGenerator)` on all objects returned by `contour_generator()`.
- Makes the docs easier to understand.
- Will make type annotations easier to write and understand.

Add ContourGenerator base class

---

tests/conftest.py
tests/test_codebase.py
tests/test_config.py
tests/test_filled.py
tests/test_lines.py
tests/test_renderer.py

This PR marks tests that require matplotlib with `@pytest.mark.needs_mpl` and moves mpl-related imports to within those test functions. If matplotlib is not installed, the remaining tests can be run using
```
pytest -k "not needs_mpl"
```
This is useful for increased running of tests in CI, such as when building wheels, as the only test dependencies are `numpy` an `pytest` which should be able to be installed and run in a reasonable time even on an emulated platform.

Mark tests that need mpl

---

src/mpl2005_original.cpp

Fixes issue #134.
The fix was specified in the error message, in 3 places in `mpl2005_original.cpp` . It is fine to use pybind11 equivalent of `np.resize(..., refcheck=False)` as the arrays are referenced elsewhere.
There is no testing using PyPy in CI yet, this will follow shortly.

Fix for PyPy np.resize bug

---

.github/workflows/test.yml

This adds PyPy to the `test.yml` github action. We don't want to run the full test suite because in the absence of matplotlib wheels for that particular version of PyPy we will have to compile matplotlib ourselves within the CI. Running `pytest -k "not needs_mpl"` is better as it only requires numpy.

Test PyPy in CI

---

lib/contourpy/util/mpl_renderer.py
tests/util_config.py

In renderer code, set Matplotlib backend when first needed rather than in imports at top of files.

Initialise mpl backend when first needed

---

.github/workflows/build_wheels.yml
pyproject.toml

When building wheels using cibuildwheel in github actions, run a simple test to check if the build worked OK. Do not want a big set of tests as running these tests on emulated platforms will be slow.

Run simple test after building wheels

---

pyproject.toml

Following on from #139, fixing the nested quotes that causes a problem on Windows, and avoid running tests in cibuildwheel for any platform/python combination for which a numpy wheel is not available. Also macos arm64 testing not yet supported in cibuildwheel.

Run simple test after building wheels attempt 2

---

setup.cfg

Allow install of test dependencies without codebase test dependencies.
Supersedes #146, providing the same functionality but without unnecessarily altering the standard dev workflow and without forcing doc deps install.

Allow install of test dependencies without codebase deps

---

.github/workflows/build_wheels.yml
.github/workflows/test.yml
setup.cfg
tests/conftest.py
tests/image_comparison.py
tests/test_config.py
tests/test_filled.py
tests/test_lines.py
tests/test_renderer.py

This PR adds the python 3.11 release candidate to CI, now that NumPy have release wheels for it. Testing for this excludes image tests as MPL and Pillow wheels are not yet available.

Add python 3.11 release candidate to CI

---

benchmarks/benchmarks/bench_filled_serial_chunk.py
benchmarks/benchmarks/bench_filled_threaded.py
benchmarks/benchmarks/bench_lines_serial_chunk.py
benchmarks/benchmarks/bench_lines_threaded.py
benchmarks/benchmarks/util_bench.py
src/base.h
src/base_impl.h
src/converter.cpp
src/converter.h
src/serial.cpp
src/serial.h
src/threaded.cpp
src/threaded.h

Performance improvements for some `LineType` and `FillType` using `threaded` algorithm.
Closes #59.
Moved `export_filled()` and `export_lines()` from `BaseContourGenerator` to `SerialContourGenerator` and `ThreadedContourGenerator`. The `serial` code is essentially unchanged but the `threaded` code now only uses a thread lock for creation of the NumPy arrays and the lock is released before the arrays are populated. This is usually faster, but the code is more complicated as there are essentially 2 passes. `Converter` class now has 2 version of each convert function, one that creates and populates the NumPy array and the other that only populates an array that has already been created.
Also expanded the threaded benchmarks to include all line and fill types, and switched use of …

Shorter threaded lock

---

src/serial.cpp

This PR changes the cache initialisation for `name="serial"` to be one chunk at a time rather than all at once if there is more than one chunk. Although doing this a chunk at a time is slightly slower as boundaries between chunks are processed more than once, there is the possibility of a performance improvement as the identification of `NO_STARTS_IN_ROW` and `NO_MORE_STARTS` occur chunk-wise, making them more useful.
There is no significant change in performance for chunked `dataset="random"` benchmarks, but there is a major improvement for `dataset="simple"`. Here is selected output from `asv compare` between `main` and this PR branch:
```
before       after        ratio
78.7±0.4ms   73.3±0.6ms   0.93  time_lines_serial_chunk('serial', 'simple', <LineType.ChunkCombinedOffset: 104>, 'no …
```

Init cache by chunk if more than 1 chunk

---

tests/test_filled.py
tests/test_lines.py

This adds line and fill chunked tests that do not generate images so that there are some chunked tests performed if image tests are disabled.

Add non-image chunked tests

---

tests/test_filled.py
tests/test_lines.py
tests/util_test.py

In threaded tests that returned non-chunked lines or fill the order of the lines/polygons is not deterministic so they have to be sorted for test comparison. Previously the sorting code wasn't robust enough; it was fine for Linux all the time but there was an occasional erroneous test failure on macOS. This PR makes the test sorting fully robust.

Better sorting in threaded tests

---

pyproject.toml

Do not specify `build` in `requires` key of `pyproject.toml`.  The key is used to specify packages used by the build *backend*.  However, `build` is the build *frontend*, and only one of the many.  Listing it as a requirement means that all frontends will unnecessary install `build` as part of the build environment, i.e. `build` will install itself inside the venv to build wheel even though it is never used there.  Installing the package from source via `pip` does not require `build` at all.

Remove unnecessary `build` dep from `pyproject.toml`

---

docs/installation.rst
lib/contourpy/__init__.py
tests/test_filled.py
tests/test_lines.py

This PR corrects the `thread_count` in chunked tests. If unspecified and `name="threaded"` it defaulted to the number of cores available when sometimes it should have been limited to just 1.
Helps but does not fix #163.
Also added docs to show how to exclude image and threaded tests when running `pytest`.

Correct thread count in chunked tests

---

README.md
docs/conf.py
docs/installation.rst
setup.cfg

Now that conda packages have been release on the Anaconda default channel (https://anaconda.org/anaconda/contourpy), this PR adds installation docs and a github badge.

Add Anaconda defaults installation docs and github badge

---

.github/workflows/test.yml
src/mpl2014.cpp
src/mpl2014.h

Fixes issue #167.
Builds and installs the latest `cppcheck` (2.9) in Linux CI, and comments out the unused `mpl2014` cache writing functions.

Install cppcheck 2.9 from source in Linux CI

---

benchmarks/README.md
src/base_impl.h
src/serial.h
src/threaded.cpp
src/threaded.h
tests/test_filled.py
tests/test_lines.py

This PR implements correct acquiring and releasing of the GIL within multithreaded code so that creation of and access to Python objects is restricted to a single thread at a time. Acquiring and releasing the GIL occurs within the lifetime of `ThreadedContourGenerator.Lock` objects.
The `threaded` algorithm is now robust for both CPython and PyPy.
Also re-enabled PyPy threaded tests that were previously skipped when they were not reliable.
Fixes #158 and #163.

Correctly acquire and release GIL in multithreaded code

---

.github/workflows/test.yml

Add a build and test run for PyPy 3.9 to CI.

Add PyPy 3.9 to CI

---

benchmarks/plot_benchmarks.py
docs/_static/chunk_filled_random.svg
docs/_static/chunk_filled_simple.svg
docs/_static/chunk_lines_random.svg
docs/_static/chunk_lines_simple.svg
docs/_static/filled_random_1000.svg
docs/_static/filled_random_1000_render.svg
docs/_static/filled_simple_1000.svg
docs/_static/filled_simple_1000_render.svg
docs/_static/lines_random_1000.svg
docs/_static/lines_random_1000_render.svg
docs/_static/lines_simple_1000.svg
docs/_static/lines_simple_1000_render.svg
docs/_static/threaded_filled_random.svg
docs/_static/threaded_filled_simple.svg
docs/_static/threaded_lines_random.svg
docs/_static/threaded_lines_simple.svg
docs/benchmarks/calculation.rst
docs/benchmarks/chunks.rst
docs/benchmarks/index.rst
docs/benchmarks/rendering.rst
docs/benchmarks/threads.rst

This updates the benchmark section of the docs in line with recent changes to the threaded code. In fact the threaded changes are insignificant, much more significant are changes to overall `serial` vs `mpl2005` and `mpl2014` speed due to change in OS (Ubuntu 22.04) and version of Python used to run the benchmarks (3.10.6). But overall conclusions are unchanged.

Update benchmarks in line with recent code changes

---

.github/workflows/test.yml

This PR modifies the existing debug CI run so that it builds a debug version of numpy (i.e. exceptions enabled) from sdist. This will help to find problems such as that of issue #163 earlier.

Use numpy debug build in debug CI run

---

.github/workflows/build_wheels.yml

Update `setup-qemu-action` to v2 as recommended when building v1.0.6 wheels.

Update setup-qemu-action to v2

---

.github/workflows/test.yml
pyproject.toml
setup.cfg

Drop support for CPython and PyPy 3.7. NumPy did this back in mid-August.

Drop support for Python 3.7

---

pyproject.toml

This removes two unneeded doc build dependencies. Use of latest `sphinx-rtd-theme` is sufficient now.

Remove unneeded doc dependencies

---

.github/workflows/test.yml

Add scheduled CI test run on Sunday mornings, and allow `workflow_dispatch` as well.

Add scheduled CI test run

---

README.md
docs/_static/contourpy_logo_horiz.svg
docs/_static/contourpy_logo_horiz_white.svg
docs/_static/contourpy_logo_vert_white.svg

Change logo in README so that it is displayed with off-white text in dark mode rather than black.

Enable dark mode logo in README

---

src/base_impl.h

Change to a single `if` statement in the `serial`/`threaded` C++ code. The original code was functionally equivalent, but this is better, more explicit, code.

Improved if statement

---

docs/changelog.rst
docs/conf.py

Streamline links to github PRs and users in changelog using `sphinx.ext.extlinks`.

Improve github links in docs

---

tests/test_filled.py
tests/test_lines.py

Add new tests:
- Non-finite `z` array (plus and minus `np.inf` and `np.nan`)
- `upper_level < lower_lower` when calling `filled()`

Test nonfinite z and decreasing zlevel for filled

---

.github/CODE_OF_CONDUCT.md
.github/workflows/test.yml
.pre-commit-config.yaml
docs/conf.py
docs/installation.rst
pyproject.toml
src/chunk_local.cpp
tests/test_codebase.py

This adds a `.pre-commit-config.yaml` to the repo with a few standard pre-commit hooks, and moves `flake8` and `isort` tests from `test_codebase.py` to the pre-commit. Also added some contributor notes to the docs to explain how to install and use it, and added running it as part of CI.

Add git pre-commit

---

.github/workflows/test.yml
tests/test_renderer.py

Add bokeh tests to CI. Using the `debug` CI run as this will ultimately be the coverage CI run which wants the maximum number of tests run and debug mode so that C++ asserts are included in the coverage report.

Add bokeh tests to CI

---

tests/test_filled.py

Fix an error in `test_filled_decreasing_levels` where the kwarg `name` was being ignored.

Correct missing name kwarg in test_filled_decreasing_levels

---

docs/api/util.rst
lib/contourpy/util/bokeh_renderer.py
lib/contourpy/util/mpl_renderer.py
lib/contourpy/util/renderer.py

This PR adds a new abstract base class `Renderer` that defines the interface that the concrete derived classes `BokehRenderer` and `MplRenderer` implement.

Add abstract base class Renderer

---

lib/contourpy/__init__.py
lib/contourpy/_contourpy.pyi
lib/contourpy/chunk.py
lib/contourpy/enum_util.py
lib/contourpy/util/bokeh_renderer.py
lib/contourpy/util/bokeh_util.py
lib/contourpy/util/data.py
lib/contourpy/util/mpl_renderer.py
lib/contourpy/util/mpl_util.py
lib/contourpy/util/renderer.py
pyproject.toml

This PR adds type annotations for the `lib/contourpy` directory, and is the start of adding type annotations to the whole library including tests and benchmarks.
The file `_contourpy.pyi` contains the type annotations for the `pybind11`-wrapped C++ shared library. It was originally created using `pybind11-stubgen` (https://github.com/sizmailov/pybind11-stubgen) and then modified by hand.
Tested using `mypy 0.991` by running `mypy` in the top-level directory. Eventually this will be set up to run in `pre-commit`.
Observations:
1. Valid algorithm `name` values are just strings. It may be more correct to use `Literal` instead but this will limit the allowed names to a specific set rather than allowing the future possibility of plugins registering new algorithms by name.
2. `matplotlib` isn't …

Type annotations for lib directory

---

pyproject.toml
tests/conftest.py
tests/image_comparison.py
tests/test_codebase.py
tests/test_config.py
tests/test_constructor.py
tests/test_enum.py
tests/test_filled.py
tests/test_lines.py
tests/test_misc.py
tests/test_renderer.py
tests/test_static.py
tests/test_z_interp.py
tests/util_config.py
tests/util_test.py

This PR adds type annotations for the `tests` directory, following on from #199.
There are some improvements to `util_config.py` to make better use of inheritance, improving the code quality and making the typing easier.  There also improvements to the code that checks that the data returned from `lines()` and `filled()` in `util_test.py`, `test_filled.py` and `test_lines.py`.

Type annotations for test directory

---

benchmarks/benchmarks/bench_base.py
benchmarks/benchmarks/bench_filled_mpl20xx.py
benchmarks/benchmarks/bench_filled_mpl20xx_render.py
benchmarks/benchmarks/bench_filled_serial.py
benchmarks/benchmarks/bench_filled_serial_chunk.py
benchmarks/benchmarks/bench_filled_serial_quad_as_tri.py
benchmarks/benchmarks/bench_filled_serial_quad_as_tri_render.py
benchmarks/benchmarks/bench_filled_serial_render.py
benchmarks/benchmarks/bench_filled_threaded.py
benchmarks/benchmarks/bench_lines_mpl20xx.py
benchmarks/benchmarks/bench_lines_mpl20xx_render.py
benchmarks/benchmarks/bench_lines_serial.py
benchmarks/benchmarks/bench_lines_serial_chunk.py
benchmarks/benchmarks/bench_lines_serial_quad_as_tri.py
benchmarks/benchmarks/bench_lines_serial_quad_as_tri_render.py
benchmarks/benchmarks/bench_lines_serial_render.py
benchmarks/benchmarks/bench_lines_threaded.py
benchmarks/benchmarks/util_bench.py
benchmarks/loader.py
benchmarks/plot_benchmarks.py
pyproject.toml

Adding type annotations for the `benchmarks` directory, following on from #199 and #200.

Type annotations for benchmarks directory

---

lib/contourpy/util/mpl_renderer.py

A single-line change that replaces the one and only call of `matplotlib.Axes.scatter()` with `matplotlib.Axes.plot()` instead. Test images generated by `MplRenderer` are identical with this. This is a potential fix for a bug that occurs on `sparc64` hardware, see issue #196 for information.
Regardless of whether it fixes the `sparc64` bug or not, I would rather use `plot` than `scatter` anyway.

Replace mpl scatter call with plot instead

---

src/base_impl.h

This removes an unnecessary `else if` statement, replacing it with an `else`.

Minor improvement to get_boundary_start_point

---

MANIFEST.in
docs/sphinxext/name_supports.py
docs/sphinxext/plot_directive.py
pyproject.toml

This completes the `mypy` configuration to allow checking of type annotations.
`mypy` is not in `pre-commit` yet, but is run manually from the command line using:
```
pip install -ve .[mypy]
mypy
```
The `mypy` dependencies also pull in the `bokeh` ones.

Complete mypy configuration

---

pyproject.toml

This is required to support pyproject.toml-based installs. 
Thanks to @hroncok for pointing this out at https://github.com/contourpy/contourpy/pull/181#discussion_r1071996338

Bump required setuptools version to 61

---

src/base.h
src/base_impl.h

This rearranges a few of the functions in the serial/threaded code so that they are in the preferred alphabetical order. There are no functional changes.

Rearrange functions alphabetically

---

docs/conf.py

The presence of typehints in the API docs make them hard to understand and is unnecessary given the human-readable types in the docstrings. This PR removes them from the API docs.

Remove typehints from API docs

---

docs/api/top.rst

The current sphinx documentation does not include `ContourGenerator.default_fill_type` or `default_line_type`, as `pybind11` does not deal with static property docstrings very well. This adds explicit entries in the docs for these two.

Add explicit sphinx docstrings for default_fill_type and default_line_type

---

src/wrap.cpp

Two sets of improvements to C++ docstrings:
- Explicit use of `py::arg` to clarify argument names
- Use the same docstrings for all the various `ContourGenerator` classes

C++ docstring improvements

---

pyproject.toml

Use a single author in the `authors` section of `pyproject.toml`, as recommended by @QuLogic in https://github.com/contourpy/contourpy/pull/181#discussion_r1166083245.

Correct authors section in pyproject.toml

---

pyproject.toml

NumPy no longer build and upload universal2 wheels to PyPI, so follow that lead. See https://github.com/numpy/numpy/pull/20787.

Drop building universal2 wheels

---

meson.build

Since meson 1.1.0 is required, it is simple to take advantage of the new-in-1.1.0 builtin dependency for pybind11. It will automatically handle the gory details of pybind11-config.

meson: simplify pybind11 dependency lookup

---

.cirrus.yml
.github/workflows/test.yml
.gitignore
docs/api/util.rst
lib/contourpy/_contourpy.pyi
lib/contourpy/util/__init__.py
lib/contourpy/util/_build_config.py.in
lib/contourpy/util/meson.build
meson.build
pyproject.toml
src/meson.build
src/wrap.cpp
tests/test_build_config.py

Fixes the 4th and 5th items of issue #224.
This PR saves build configuration determined at build time in a Python file so that it is available at runtime via `contourpy.util.build_config`, e.g.
```python
from contourpy.util import build_config
print(build_config())
```
Example output (pretty printed with simplified directories):
```
{'b_ndebug': 'if-release',
'b_vscrt': 'from_buildtype',
'build_cpu': 'aarch64',
'build_cpu_endian': 'little',
'build_cpu_family': 'aarch64',
'build_cpu_system': 'darwin',
'build_dir': '/somedir/.mesonpy-l7paevlc/build/lib/contourpy/util',
'build_options': '-Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md '
'-Doptimization=3 -Dvsenv=True '
'--native-file=/somedir/.mesonpy-l7paevlc/build/meson-python-native-file.ini',
'buildtype': 'release', …
```

Add build_config to store and show build configuration info

---

.github/workflows/test.yml
pyproject.toml
tests/test_codebase.py

Run `mypy` in CI. Added it to `test_codebase` rather than in `pre-commit` so that it runs in the development virtual environment rather than the `pre-commit` one. If `mypy` is not installed the test is skipped.
It runs in the `debug` CI run as that already has the `bokeh` dependencies installed, so just need to add the extra `mypy` ones.

Run mypy in CI

---

pyproject.toml

Bump meson-python to 0.13.1. This picks up the `$ARCHFLAGS` fix to allow cross-compilation on macOS (mesonbuild/meson-python#407).

Bump meson-python to 0.13.1

---

benchmarks/asv.conf.json
pyproject.toml
src/meson.build

Using the default `meson-python` `buildtype` of `release`. This gives `-O3` optimisation by default and excludes debug information which is what is has historically been the case for `contourpy` PyPI wheels. For development and coverage purposes a `buildtype` of `debug` will probably be used, as illustrated in GHA `test.yml`.
Not yet adding any specific extra compiler flags, most of which are extra warning detections.
Also updated the `asv` config to run benchmarks and confirmed that there are no statistically-significant reductions in performance when running the benchmark suite. Updated timings to follow.
FIxes the first two items of issue #224.

Set default meson build type

---

src/mpl2005_original.cpp

`nparts2` variable in `mpl2005_original.cpp` is  never used so can be removed.

Remove unused variable nparts2 in mpl2005

---

.github/workflows/test.yml
pyproject.toml

This PR adds the calculation of code coverage in CI and uploading it to codecov.io. The `lcov` commands to extract the C++ coverage follow `Matplotlib`.

Add codecov github action

---

src/mpl2014.cpp
src/mpl2014.h

Various `mpl2014` functions of C++ helper classes are unused, so deleting them. Identified by code coverage. They were used in the original `matplotlib` code as the helper classes were shared with other algorithms, particularly `tricontour`.

Removed unused mpl2014 functions

---

src/mpl2014.cpp
src/mpl2014.h

This is an improvement to the error handling of chunk calculations in `mpl2014`. There is no functional change.
The problem only manifested itself if `assert`s were enabled (i.e. `NDEBUG` not defined) and a `z` array passed directly to the C++ constructor (so not via `contour_generator`) with a number of dimensions other than 2. A debug `assert` would fail before the incorrect number of dimensions raised an error. This would only ever have occurred in a bespoke build with the asserts specifically enabled.
The improvement is to better handle the inconsistent `z` dimensions and chunk sizes before the correct exception is raised.
An explicit test for this will be added in a follow-up PR that tests the internal (`wrap.cpp`) API.

Improve mpl2014 chunk count error handling

---

pyproject.toml
src/base_impl.h
src/mpl2005.cpp
src/mpl2014.cpp
tests/test_internal.py

This adds a new test file `test_internal.py` to test the internal C++ API defined in `wrap.cpp`. The functions tested are constructors and the private `_write_cache` function.  Usually the constructors would not be accessed directly from user code as it is better practice to use the `contour_generator` function as it performs extra argument checking and conversion.
Also improved the exception message for negative chunk sizes, across all algorithms.

Add internal API tests

---

.github/workflows/test.yml

Add python 3.12-dev to CI. Not using image tests as do not want to compile matplotlib from source.

Add python 3.12-dev to CI

---

.github/workflows/test.yml

This PR adds CI runs for `musllinux` on `x86_64`, and `manylinux` on `ppc64le` and `s390x`. All three run in docker containers using the same images used by `cibuildwheel`.
There are no `musllinux` wheels available yet for `numpy` and `matplotlib`, so the `musllinux` run builds `numpy` from source and tests using only non-image tests. The next `numpy` release (1.25) will include `musllinux` wheels so they will be used rather than building from source here.
The `ppc64le` and `s390x` CI runs are on emulated hardware using QEMU. Neither `numpy` nor `matplotlib` produce wheels for these architectures, but there are `conda` packages available that are fairly up-to-date. Hence the CI runs for them here use `conda` and run all of the tests, including image tests, except for a few of the bigger …

Add tests for musllinux (on x86_64), ppc64le and s390x

---

README_simple.md
pyproject.toml

Workaround for #208.
PyPI does not render the `<picture>` tag that is used in the github README to support dark and light mode and it doesn't seem likely that this will supported in the short term. Hence this adds a new `README_simple.md` that is the same as the original `README.md` but with the `<picture>` tag removed.
Also added a couple more `project.urls` to the `pyproject.toml`.

Add simpler README for PyPI

---

.github/workflows/test.yml

Temporarily disable python 3.12-dev tests in CI. They were working last week but not this, and there is no rush.

Temporarily disable python 3.12 tests [skip ci]

---

.github/workflows/build_wheels.yml
MANIFEST.in
lib/contourpy/meson.build
meson-cross.ini
pyproject.toml

Update to wheel building github action that uses `cibuildwheel` in line with switch to `meson` build system.
Changes:
1. No longer building any 32-bit wheels, in line with what `numpy` and `matplotlib` are planning.
2. Added building of `ppc64le` and `s390x` wheels, on `manylinux` only.
3. Cross-building of `aarch64` macos wheels on `x86_64` is obtained using a workaround to find `pybind11-config` that won't be needed when `meson` 1.2.0 is reieased, which should be soon.
4. Printing `build_config` as part of post-build tests to confirm cross-build and so are working as expected.
5. Still building `musllinux` wheels on `x86_64` only.

Update wheel building using meson

---

lib/contourpy/util/meson.build

It has been awkward checking cross-compilation settings when building wheels for PyPI and conda packages, so this prints some key build configuration settings earlier in the build process in the meson summary section.

Print config summary during build process

---

.github/workflows/test.yml

Can now successfully build numpy 1.25.0 from source on Python 3.12.0-beta.3 using
```
python -m pip install --upgrade pip setuptools wheel
pip install -v cython
pip install -v --no-binary=numpy numpy --no-build-isolation
```
and then build contourpy from source in the usual manner
```
python -m pip install -v .
```

Build and test on Python 3.12

---

.pre-commit-config.yaml

The `ruff` repo has moved its github organisation, this updates the `pre-commit` link. See scientific-python/cookie#200.

Update ruff repo link

---

.github/workflows/build_wheels.yml
build_requirements.txt
meson-cross.ini
meson.build
pyproject.toml

Update `meson` to `1.2.0` which handles `pybind11` correctly when cross-compiling so no longer need to use our own `meson-cross.ini`.

Update meson to 1.2.0

---

.github/workflows/test.yml
tests/test_bokeh_renderer.py

This reenables the bokeh images tests in CI after the improvements of #261.
Chromedriver path is hardcoded which isn't ideal but will allow the CI to run and can be improved in future.

Reenable bokeh tests in CI

---

.github/workflows/test.yml
tests/conftest.py
tests/test_bokeh_renderer.py

This adds a new `--driver-path` pytest option to override the path to the chrome driver that is used for Bokeh renderer tests. By default this is unset and selenium will follow its normal process for determining the path. For usage see `.github/workflows/test.yml` which sets it to `/snap/bin/chromium.chromedriver` in the appropriate github action run which has many browsers installed and we want to ensure the tests use the correct one.

Add --driver-path pytest option to specify chrome driver path

---

pyproject.toml

Pinning numpy to `< 2.0` as recommended in numpy/numpy#24300 for packages that use the NumPy C API, as done here via `pybind11`.
Leaving CI without numpy version pins, will address problems if/when they come up.

Pin numpy < 2.0

---

.github/workflows/test.yml
build_requirements.txt
docs/conf.py
docs/developer_guide.rst

This removes the explicit `ninja` requirement in `build_requirements.txt` to keep it in line with the `[build-system]` `requires` section of `pyproject.toml`. See #260 for the change in `pyproject.toml`, and some discussion.
Also added minimal developer docs about needing a C++ compiler, etc.

Remove ninja build requirements

---

.github/workflows/build_wheels.yml
.github/workflows/test.yml
.pre-commit-config.yaml
pyproject.toml

Use numpy `1.26.0rc1` that supports Python 3.12 for tests and wheel building. Also update some github actions.

Test and build wheels for python 3.12 using numpy RC

---

lib/contourpy/_version.py
meson.build

Prepare for 1.1.1rc1 which supports Python 3.12. Changelog not updated yet, will be done in the actual release.

Prepare for 1.1.1rc1

---

.github/workflows/test.yml

Add Windows 32-bit testing to CI. I am deleting the GNU linker so that it cannot be confused with the MSVC one, which I am not proud of, but if it is good enough for numpy then I am happy to do the same:
https://github.com/numpy/numpy/blob/34d6693b6e763c42ffa09ad050cce7f429e15ec0/tools/wheels/cibw_test_command.sh#L21-L24

Add Windows 32-bit testing to CI

---

.cirrus.yml
.github/workflows/test.yml
pyproject.toml

Remove support for CPython 3.8 and PyPy 3.8, in line with NumPy and Matplotlib.

Remove support for CPython 3.8 and PyPy 3.8

---

.github/workflows/test.yml

This adds a CI run using numpy nightly wheels as described at https://scientific-python.org/specs/spec-0004. It will therefore test against the latest numpy 2.0 build.
Not using matplotlib nightly wheels as they pin to numpy < 2.0 and only really need to test against install dependencies rather than test dependencies.

Test against numpy nightly wheels

---

.cirrus.yml
.github/workflows/test.yml
docs/developer_guide.rst
pyproject.toml

Various CI updates now that it is possible to test using numpy, matplotlib and pillow wheels for CPython 3.12, PyPy 3.9 and musllinux.
- Allow `noblas` when compiling numpy from source.
- Correctly set debug option when compiling numpy from source.
- Use image tests for:
- CPython 3.12
- PyPy 3.9
- musllinux

CI updates for CPython 3.12, PyPy 3.9 and musllinux

---

.github/workflows/build_wheels.yml
.github/workflows/test.yml

Set `python-version` in pre-commit github action to avoid this error:
```
The `python-version` input is not set. The version of Python currently in `PATH` will be used.
```

Set python version in pre-commit github action

---

tests/test_filled.py
tests/test_lines.py

Adding tests to confirm that contour levels of `-np.inf` and `np.inf` are valid on all platforms. These are useful, for example, to produce filled contours from a level `z` upwards which would be achieved using
```python
from contourpy import contour_generator
import numpy as np
cg = contour_generator(...)
filled = cg.filled(1.0, np.inf)
```
Doc update with examples to follow in a separate PR.

Test contour levels that are +/-np.inf

---

lib/contourpy/__init__.py
lib/contourpy/enum_util.py
lib/contourpy/util/bokeh_renderer.py
lib/contourpy/util/mpl_renderer.py
lib/contourpy/util/renderer.py
tests/test_bokeh_renderer.py
tests/test_enum.py
tests/test_renderer.py

Support the use of strings instead of enums in `Renderer` functions `filled()` and `lines()`.
Also improved error messages when converting strings to enums.

Support strings instead of enums in renderer functions

---

lib/contourpy/util/_build_config.py.in
lib/contourpy/util/bokeh_renderer.py

Add `versionadded` sphinx directive to record the version at which new classes/functions/arguments were added. Initially used for:
- `_build_config` function (version added 1.1.0).
- `webdriver` argument to `BokehRenderer.save` and `save_to_buffer` functions (version added 1.1.1).

Use versionadded sphinx directive

---

tests/test_config.py
tests/util_config.py

Possible fix for #286.
This adds a new function `Config.clear` that is called at the end of config tests to clear up Matplotlib resources (`Figure` and `Axes` objects). It shouldn't really be needed as the resources will eventually be garbage collected, but these tests do create large numbers of `Axes` objects which can cause intermittent test failures using `pytest` on PyPy. Locally this does seem to fix the problem, but it is not possible to be completely sure as the failures are intermittent. Regardless, it is better design anyway.

Explicitly clear resources in Config test classes

---

.github/workflows/test.yml

Now that CPython 3.12 has been officially released, use `3.12` rather than `3.12-dev` with `setup-python` in CI.

Switch from using python 3.12-dev to 3.12 in CI

---

docs/api/top.rst
lib/contourpy/__init__.py
lib/contourpy/_contourpy.pyi
lib/contourpy/dechunk.py
lib/contourpy/meson.build
lib/contourpy/util/mpl_renderer.py
src/fill_type.h
src/line_type.h
tests/test_dechunk.py

Adding two new functions `dechunk_lines` and `dechunk_filled`, which accept any `lines` or `filled` respectively and move the 2nd and subsequent chunks, if present, into the first chunk. These will be useful for upcoming examples of using ContourPy output with other libraries.
User guide docs will follow in a separate PR.

Add new functions dechunk_lines and dechunk_filled

---

tests/conftest.py

Use better names for enums when reporting parameterised tests via a `pytest_make_parametrize_id` function in `conftest.py`.
Example before:
```
$ pytest -v tests/test_dechunk.py::test_dechunk_lines
tests/test_dechunk.py::test_dechunk_lines[0-line_type0]
tests/test_dechunk.py::test_dechunk_lines[0-line_type1]
tests/test_dechunk.py::test_dechunk_lines[0-line_type2]
tests/test_dechunk.py::test_dechunk_lines[0-line_type3]
tests/test_dechunk.py::test_dechunk_lines[2-line_type0]
tests/test_dechunk.py::test_dechunk_lines[2-line_type1]
tests/test_dechunk.py::test_dechunk_lines[2-line_type2]
tests/test_dechunk.py::test_dechunk_lines[2-line_type3]
```
and after:
```
$ pytest -v tests/test_dechunk.py::test_dechunk_lines
tests/test_dechunk.py::test_dechunk_lines[0-Separate] …
```

Use better names for enums when reporting parameterised tests

---

lib/contourpy/util/bokeh_util.py
lib/contourpy/util/mpl_renderer.py
lib/contourpy/util/mpl_util.py

Reuse converter functions in `Renderer` classes. This includes use of `convert_fill_type` and `convert_line_type` as well as some of the low-level private offsets to/from code functions.

Use converter functions in renderers

---

docs/conf.py
docs/user_guide/line_type.rst
lib/contourpy/_contourpy.pyi
lib/contourpy/convert.py
lib/contourpy/dechunk.py
lib/contourpy/util/bokeh_util.py
lib/contourpy/util/mpl_util.py
src/base.h
src/base_impl.h
src/chunk_local.h
src/line_type.cpp
src/line_type.h
src/serial.cpp
src/threaded.cpp
src/util.cpp
src/util.h
src/wrap.cpp
tests/test_dechunk.py
tests/test_lines.py
tests/test_misc.py
tests/util_test.py

This adds a new `LineType` `ChunkCombinedNan` to the `serial` and `threaded` algorithms which returns a single numpy array per chunk containing the x, y coordinates of all the points in that chunk with lines separated by NaN. This is the internal format used in both Bokeh and HoloViews so it will simplify and improve the performance of those libraries for contour lines. Closes #289.
Example:
```python
from contourpy import contour_generator
z = [[0, 0], [1, 1], [0, 0]]
cont_gen = contour_generator(z=z, line_type="ChunkCombinedNan")
cont_gen.lines(0.5)
```
produces
```
([array([[0. , 0.5],
[1. , 0.5],
[nan, nan],
[1. , 1.5],
[0. , 1.5]])],)
```
The returned tuple only ever contains one list so strictly speaking the tuple is not required, but it is used here for consistency with all other …

Add new LineType ChunkCombinedNan

---

docs/benchmarks/threads.rst
docs/index.rst
docs/user_guide/name.rst
docs/user_guide/threads.rst

Removing warnings that the `threaded` algorithm is experimental. It has been around for long enough and used enough to demonstrate that there is nothing fundamentally wrong with the approach.

Remove threaded experimental warnings

---

lib/contourpy/array.py
lib/contourpy/convert.py
lib/contourpy/dechunk.py
lib/contourpy/meson.build
lib/contourpy/util/bokeh_util.py
lib/contourpy/util/mpl_util.py

There are various point/code/offset array manipulation functions in `convert.py` and `dechunk.py`. This PR moves them out into a separate file `array.py` and gives them more consistent function and argument names. These are only intended to be used internally within ContourPy so they are not exported from the top-level module.

Move array manipulation functions into separate file

---

lib/contourpy/array.py
tests/test_convert.py
tests/test_dechunk.py

Cast offsets to `np.int64` before calling `np.insert` to avoid mixing signed and unsigned ints that causes UFunc error. Also improved tests for `convert` functions to avoid future regression.
Fixes #299.

Cast offsets to np.int64 before calling np.insert

---

lib/contourpy/util/bokeh_renderer.py
lib/contourpy/util/bokeh_util.py

Now that we have `LineType.ChunkCombinedNan`, always use it to render lines in `BokehRenderer`. Whatever lines are passed to`BokehRenderer.lines` are converted via `convert_line_type` and `dechunk_lines` to give a single NaN-separate points array which is used to create a Bokeh `line` glyph rather than the `multi_line` glyph used previously here.

Always use LineType.ChunkCombinedNan for lines in Bokeh

---

lib/contourpy/array.py
lib/contourpy/convert.py
lib/contourpy/util/mpl_util.py
pyproject.toml

Use explicit `dtype` in `np.concatenate` calls. The recent additions of `np.concatenate` in `array.py` (and some other places) has worked fine in CI until some very recent changes in the numpy 2.0 nightlies. To avoid problems concatenating arrays with different `dtype`s it is best to explicitly specify the required `dtype`.
The one exception is in `mpl_util.py` where offsets are calculated and used immediately without having to be a particular `dtype`.
This kwarg needs `numpy >= 1.20`.

Use explicit dtype in np.concatenate calls

---

.cirrus.yml
.github/workflows/test.yml
pyproject.toml

NumPy has starting building musllinux aarch64 wheels (numpy/numpy#24993) so let's follow their lead. Building the wheels is easy thanks to cibuildwheel, but we will follow the usual policy of only building wheels for platforms we are actively testing on in CI. When numpy release such wheels it will be simplest to test using QEMU on a github runner in the same way as is currently done for musllinux x86_64, but building numpy from source within emulation is a slow process. So here using some of the limitied Cirrus CI resources to test on ARM64 hardware.

Test and build wheels for musllinux aarch64

---

.github/workflows/test.yml

Running tests on PyPy takes about 40 minutes whereas the next slowest tests (debug with coverage) are less than half that. Here excluding 'big' tests for PyPy, which are `test_filled_random_big` and `test_lines_random_big`.

Do not run 'big' tests on PyPy

---

lib/contourpy/array.py
tests/test_array.py

Add unit tests for `array.py` in `test_array.py`. There is some extra validation in the `array` functions but this only checks the `dtype`, `ndim` and `shape` of code/offset/point arrays, it never walks the arrays as this might be very slow.

Add unit tests for array.py

---

tests/test_convert.py

There is a single code path in `coverage.py` that is not covered by tests, corresponding to a chunk with a single filled polygon (with or without holes) being converted from `LineType.ChunkCombinedOffsetOffset` to `LineType.OuterOffset`. This PR fixes it by running the convert tests using an extra smaller chunk size.

Complete coverage of convert.py

---

docs/api/top.rst
lib/contourpy/__init__.py
lib/contourpy/convert.py
lib/contourpy/util/bokeh_util.py
lib/contourpy/util/mpl_renderer.py
tests/test_convert.py

Rename convert functions from `convert_fill_type` to `convert_filled` and from `convert_line_type` to `convert_lines`. This fits in better with the `dechunk` names, and allows future inclusion of `multi_lines` functions that take a sequence of lines, etc.

Rename convert functions

---

lib/contourpy/array.py
lib/contourpy/convert.py
lib/contourpy/meson.build
lib/contourpy/typecheck.py
tests/test_array.py
tests/test_typecheck.py

Some improvements to the array checking functions `check_code_array`, `check_offset_array` and `check_point_array`:
- Move them to their own file `typecheck.py` (more functions will follow)
- Explicit checks for these 3 functions in `test_typecheck.py`
- Check the first element of code and offset arrays, should be 1 and 0 respectively
- Separate `split_by_offsets` into the two more specific `split_codes_by_offsets` and `split_points_by_offsets`
- Correctly name two of the test functions in `test_array.py`

Improve array checking functions

---

.cirrus.yml

Need to limit CirrusCI usage as much as possible as availability is reduced. Hence run on PRs but not on merges to `main` branch.

Only run CirrusCI on PRs, not on merges to main

---

lib/contourpy/convert.py
lib/contourpy/dechunk.py
lib/contourpy/typecheck.py
pyproject.toml
tests/test_typecheck.py

This adds extra internal validation functions `check_filled` and `check_lines` to the `convert_*` and `dechunk_*` functions, to check that the inputs are reasonable. They don't check absolutely everything, like the array checking functions they will walk tuples and lists (e.g. chunked data) but not the contained arrays because that might take a long time.
Most of the new code is tests that all the various error modes are caught for each of the different `FillType` and `LineType`.

Extra validation when dechunking and converting contour lines and filled contours

---

src/base_impl.h
src/mpl2005.cpp
src/mpl2014.cpp
tests/test_filled.py

ContourPy has always raised a `ValueError` if `filled()` is called with a `lower_level` that is larger than the `upper_level`. This PR also raises if `lower_level == upper_level`. The exception text for both is now "upper_level must be larger than lower_level" for all algorithms.
Instead of using `filled(level, level)` use `lines(level)` instead.

Raise if call filled() with lower_level==upper_level

---

pyproject.toml

Previous release had to pre-install numpy from source on win32 for Python 3.12 as there were no binary numpy wheels for this available at the time, and it needed the `allow-noblas` option. This is no longer the case, so is not needed.

Don't preinstall numpy when building python 3.12 win32 wheels [skip ci]

---

benchmarks/plot_benchmarks.py
lib/contourpy/__init__.py
lib/contourpy/util/bokeh_renderer.py
lib/contourpy/util/mpl_renderer.py
pyproject.toml
tests/test_filled.py
tests/test_renderer.py
tests/test_typecheck.py
tests/util_config.py

Add ruff C4 rules, unnecessary `list`, `dict`, `map`, `tuple` calls.

Add ruff C4 rules

---

.cirrus.yml
.github/workflows/test.yml

Some updates to CI following the release of NumPy 1.26.2.
1. No longer need `-D=allow-noblas=true` when building NumPy from source as this is the default.
2. Availability of NumPy `musllinux_aarch64` wheels means we no longer need to build NumPy from source to test on `musllinux_aarch64`, so move those tests to github actions (QEMU+docker) from Cirrus CI.

Update CI following NumPy 1.26.2 release

---

tests/test_filled.py
tests/test_lines.py
tests/test_misc.py

All tests pass except those explicitly asserting that they are on a multicore system.  Adds a conditional skip to those which are only useful on multicore hosts.

Support running tests on unicore hosts

---

.github/workflows/test.yml

In CI we test against numpy nightly wheels, primarily to check for conformance with numpy 2.0. This PR also uses matplotlib nightly wheels for the same tests.

In nightly wheel tests use matplotlib as well as numpy nightlies

---

src/wrap.cpp

Use `"name"_a` instead of `py::arg("name")` for named arguments to `pybind11`-wrapped functions as it is more concise.

Use _a suffix instead of py::arg for pybind11 named args

---

tests/test_z_interp.py

Fixes #330.
Passing 2D vectors to `numpy.cross` is deprecated in Numpy 2.0, so here passing 3D vectors by appending a z-component of zero, and only checking the z-component of the cross product as the other 2 components are zero.

Pass 3D vectors to numpy.cross

---

.github/workflows/test.yml
tests/conftest.py
tests/image_comparison.py

Second attempt at #334.
Currently image comparison tests either pass or fail, and there is no logging of how much each generated image differs from its image baseline. This PR adds a `pytest` option `pytest --log-image-diffs` that logs all the image differences to the file `result_images/image_diffs.log`, and this is enabled in test github actions so that the logs will be added to the uploaded artifact.
It will be possible to analyse the results to see if there are any particular hardware/OS combinations that give worse results than others (although still within the allowed difference limits).
This second attempt supports use of `pytest-xdist` in which each worker process writes to its own log file and they are all combined together at the end.

Add pytest option to log image differences to CSV file, take 2

---

src/base.h
src/base_impl.h
src/contour_generator.h
src/mpl2005.cpp
src/mpl2005.h
src/mpl2014.cpp
src/mpl2014.h
src/wrap.cpp

Up until now `lines()` and `filled()` have been non-virtual C++ functions that have been separately defined in `wrap.cpp` for each of the concrete `ContourGenerator`-derived classes and so they have been resolved at runtime using the usual Python MRO. This has been acceptable as the functions have only ever been called from Python, not internally within the C++ code.
This PR makes them virtual C++ functions so that they can be called from within the C++ code without dropping back to Python, as will be required in the soon to be added functions `multi_lines()` and `multi_filled()`. Here we will have a single implementation of each `multi_*` function in the `ContourGenerator` class that calls the appropriate `lines()` or `filled()` multiple times.
Summary of changes:
1. New virtual C++ …

Make lines() and filled() virtual C++ functions

---

src/base_impl.h
src/mpl2005.cpp
src/mpl2014.cpp
src/util.cpp
src/util.h
src/wrap.cpp
tests/test_filled.py

Up until now it has been possible to use `np.nan` as either/both of `lower_level` and `upper_level` passed to `filled()`. This isn't recommended as it can give strange results such as
```python
>>> cg = contour_generator(z=[[0, 0], [1, 1]])
>>> cg.filled(np.nan, 0.5)
([array([[0. , 0.5],
[nan, nan],
[nan, nan],
[1. , 0.5],
[0. , 0.5]])], [array([0, 5], dtype=uint32)])
```
This PR prevents passing `np.nan` to `filled()` and will raise a `ValueError`. Classifying it as a bugfix as it should probably never have been allowed. It may affect downstream usage, so the next release to include this will be 1.3.0.
Use of `np.nan` in `lines()` is still permitted, it gives the same uninteresting but valid results as using `-np.inf` or `np.inf` which is an empty line set.
The C++ nan check is performed …

Prevent use of np.nan as lower or upper_level in filled()

---

lib/contourpy/util/renderer.py
tests/test_bokeh_renderer.py
tests/test_filled.py
tests/test_lines.py
tests/test_renderer.py

This adds new functions `Renderer.multi_lines` and `Renderer.multi_filled` to easily render the outputs of the recently-added (#340 ) `ContourGenerator.multi_lines` and `ContourGenerator.multi_filled`.
If a `color` kwarg is not specified then the line/filled contour sets are rendered in sequential colors from the tab10 colormap, wrapping round to the first if there are more than 10 contour sets. If a `color` is specified then it is used for all contour sets. All other kwargs are passed on to the underlying `Renderer.lines()` or `filled()` functions.
Example use:
```python
from contourpy import contour_generator
from contourpy.util.mpl_renderer import MplRenderer as Renderer
import numpy as np
cont_gen = contour_generator(z=[[1, 2], [3, 4]])
levels = np.linspace(1, 4, 10)
mf = …
```

Add new functions Renderer.multi_lines and multi_filled

---

src/base.h
src/base_impl.h
src/contour_generator.h

Streamline `multi_filled` and `multi_lines` for `serial` and `threaded` algorithms as setting various properties of the algorithm, such as whether holes are identified or not, only needs to be performed once at the start rather than for every underlying `filled` or `lines` call.

Streamlined BaseContourGenerator::multi_filled and multi_lines

---

benchmarks/benchmarks/bench_filled_mpl20xx.py
benchmarks/benchmarks/bench_filled_mpl20xx_render.py
benchmarks/benchmarks/bench_filled_serial.py
benchmarks/benchmarks/bench_filled_serial_chunk.py
benchmarks/benchmarks/bench_filled_serial_quad_as_tri.py
benchmarks/benchmarks/bench_filled_serial_quad_as_tri_render.py
benchmarks/benchmarks/bench_filled_serial_render.py
benchmarks/benchmarks/bench_filled_threaded.py
benchmarks/benchmarks/bench_lines_mpl20xx.py
benchmarks/benchmarks/bench_lines_mpl20xx_render.py
benchmarks/benchmarks/bench_lines_serial.py
benchmarks/benchmarks/bench_lines_serial_chunk.py
benchmarks/benchmarks/bench_lines_serial_quad_as_tri.py
benchmarks/benchmarks/bench_lines_serial_quad_as_tri_render.py
benchmarks/benchmarks/bench_lines_serial_render.py
benchmarks/benchmarks/bench_lines_threaded.py
tests/test_filled.py
tests/test_lines.py

Switch to using `multi_lines` and `multi_filled` in tests and benchmarks wherever possible to make the code simpler. Have kept some tests that use both the multi and non-multi approaches to demonstrate they produce the same results.

Use multi_lines and multi_filled in tests and benchmarks

---

docs/api/contourpy/other.rst
lib/contourpy/__init__.py
lib/contourpy/dechunk.py
src/wrap.cpp
tests/test_dechunk.py

Add new convenience functions `dechunk_multi_lines` and `dechunk_multi_filled` to support dechunking of the returns of `ContourGenerator.multi_lines` and `ContourGenerator.multi_filled`.

Add new functions dechunk_multi_lines and dechunk_multi_filled

---

pyproject.toml

Drop `numpy < 2.0` pin in `main` (i.e. development) branch.

Drop numpy < 2.0 pin

---

.github/workflows/test.yml

Add new CI run using earliest supported numpy. This is currently numpy 1.20, which implies python <= 3.9. This will pick up earlier matplotlib as well.

Add CI run using earliest supported numpy

---

docs/api/contourpy/other.rst
lib/contourpy/__init__.py
lib/contourpy/convert.py
tests/test_convert.py

Add new convenience functions `convert_multi_lines` and `convert_multi_filled` to support converting of the returns of `ContourGenerator.multi_lines` and `ContourGenerator.multi_filled`.

Add new functions convert_multi_lines and convert_multi_filled

---

docs/developer_guide.rst

Clarify in docs that some uses of `pip install` (e.g. on zsh) such as
```bash
python -m pip install -ve .[test]
```
need quotes around the `.[test]` so
```
python -m pip install -ve ".[test]"
```

Clarify use of quotes in pip install

---

.github/workflows/test.yml
tests/test_bokeh_renderer.py

There are two `type: ignore` comments that were needed in the test suite when using Bokeh 3.3.3 but are no longer needed with Bokeh 3.3.4. This PR removes them.
```
tests/test_bokeh_renderer.py:31: error: Unused "type: ignore" comment  [unused-ignore]
tests/test_bokeh_renderer.py:32: error: Unused "type: ignore" comment  [unused-ignore]
```

Remove unneeded type:ignore using Bokeh 3.3.4

---

lib/contourpy/array.py
lib/contourpy/convert.py
lib/contourpy/util/mpl_util.py

Fixes #353 by casting returns from `np.split` to `list` as that is how they are dealt with internally in ContourPy.

Convert return from np.split to list

---

.github/workflows/test.yml

M1 macos runner is now available on github actions for OSS projects. https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source.
Trying it out.

Run github actions on M1 mac

---

.github/workflows/build_wheels.yml
.github/workflows/test.yml

Update `upload-artifact` github action to v4. This prohibits multiple uploads to the same named artifact, so here we now have different naming conventions for artifacts and their contents.

Update upload artifact github action to v4

---

lib/contourpy/array.py
lib/contourpy/convert.py
lib/contourpy/util/mpl_util.py

Revert #354 casting return from `np.split` to list as NumPy have reverted their changes that necessitated it (numpy/numpy#25800).

Revert casting return from np.split to list

---

benchmarks/README.md
benchmarks/asv.conf.json
benchmarks/benchmarks/bench_filled_mpl20xx.py
benchmarks/benchmarks/bench_filled_mpl20xx_render.py
benchmarks/benchmarks/bench_lines_mpl20xx.py
benchmarks/benchmarks/bench_lines_mpl20xx_render.py
benchmarks/loader.py
pyproject.toml

Update `asv` to 0.6.2 as this is the first release containing fix airspeed-velocity/asv#1351 that is needed to support benchmarks with some parameter combinations skipped.

Update to asv 0.6.2

---

.github/workflows/build_wheels.yml

Some improvements to wheel building CI run in preparation for #362:
- Build wheels once a week regardless of other repo activity.
- Don't run it on forks.
- Use separate artifacts for wheels and sdist.
The upload nightly wheels action will be added at the end of this yaml file when the secret keys, etc, are set up.

Build wheels once a week, separate out sdist and wheels

---

.github/workflows/build_wheels.yml

This adds an upload nightly wheels step after building wheels.  Should only run for wheels built on the `main` branch of this repo, not forks.
Should complete #362.
Will need to merge this and kickstart a wheel build on `main` to see if it works as intended.

Add upload nightly wheels action

---

lib/contourpy/__init__.py
src/wrap.cpp

This adds more cross-references in the API docs to the explanations of how the returned data formats of `lines()` and `filled()` calls relate to the contour generator's `line_type` and `fill_type`.
Fixes #365.

Add more doc cross-references to explain returned data formats

---

.github/workflows/test.yml

Disable scheduled CI test runs on forks, only run them on the main repo, i.e. in the `contourpy` github organisation.

Disable scheduled CI test runs on forks

---

build_requirements.txt
pyproject.toml

Update pybind11 to 2.12.0. This supports NumPy 2 with no other changes required.
Replaces #369.

Update pybind11 to 2.12.0

---

.github/codecov.yml
.github/workflows/test.yml

Update `codecov-action` to v4. `token` is now required.

Update codecov-action to v4

---

.github/workflows/test.yml

Add CI runs against NumPy and Matplotlib nightly wheels on macOS and Windows. Already doing so on Linux.

Test against nightly wheels on macos and windows

---

.github/workflows/test.yml

Test the standard matrix of CI runs against numpy 2 pre-release. This is temporary, until the full release of numpy 2.0.0. Also need to install matplotlib nightly wheels, until there is a release or pre-release that supports numpy 2.

Test against numpy 2

---

.github/workflows/test.yml

With the release of Matplotlib 3.8.4 we can test against that rather than having to use Matplotlib nightly wheels to obtain support for NumPy 2.

Use numpy 2 compatible matplotlib 3.8.4

---

.github/workflows/build_wheels.yml
.github/workflows/test.yml

Update github runners, in particular use `macos-14` to build macos ARM wheels.

Update github runners

---

.github/workflows/test.yml

Both NumPy and ContourPy build using Python 3.13.0a6 so here adding it to CI. Excluding image tests as do not want to build Matplotlib or Pillow.

Add Python 3.13-dev to CI

---

.github/workflows/test.yml

Python 3.9 is now available via the `setup-python` action on `macos-14` runners, so here completing the CI matrix.

Include macos-14 python 3.9 CI run

---

.github/workflows/build_wheels.yml
.github/workflows/test.yml

When pushing to a PR, auto cancel existing github action workflows that are in progress.

Cancel concurrent github action workflows

---

.github/workflows/build_wheels.yml
pyproject.toml

Add building of Python 3.13 wheels and uploading to [Scientific Python Nightly Wheels](https://anaconda.org/scientific-python-nightly-wheels).
Using `CIBW_PRERELEASE_PYTHONS` to pick up pre-release Python 3.13, and for testing using NumPy nightly wheels. Excluding linux `aarch64` wheels (`manylinux` and `musllinux`) from tests as there are no NumPy nightly wheels for them yet.

Build Python 3.13 wheels and upload to nightly wheels

---

docs/user_guide/calculate/quad_as_tri.rst
docs/user_guide/calculate/z_corner_mask.rst
docs/user_guide/calculate/z_interp.rst

Use `multi_lines` and `multi_filled` in examples in the docs in preference to loops of `lines` and `filled`.

Use multi_lines/filled in examples in docs

---

docs/changelog.rst

Forward port v1.2.1 changelog to `main` branch in preparation for v1.3.0 release.

Forward port v1.2.1 changelog

---

src/meson.build

Revert the MSVC workaround in PR #391 as it has been fixed upstream.

Revert MSVC runtime workaround in PR #391

---

.github/workflows/test.yml

Update the `musllinux` docker image versions used in CI from 1.1 to 1.2, so that the `aarch64` run uses NumPy 2.0 rather than 1.26.4.

Update musllinux docker image versions in CI to 1.2

---

pyproject.toml
tests/test_minimal.py

Add a new test script `test_minimal.py` to perform minimal (not exhaustive) testing of all 4 algorithms and all line and fill types. It is based on the line and fill type pages in the docs, but with 2 chunks so that the `threaded` algorithm can be tested. The only required test dependencies are `numpy` and `pytest`.
Replaced the extremely minimal testing when building wheels with this, and intend to do the same with `conda-forge`, `pyodide` and `emscripten-forge` recipes.

Add minimal test script

---

tests/util_config.py

Fixes issue #401.
The axes return type of `pyplot.subplots` has changed in Matplotlib 3.9.1 causing `mypy` failures in some test code in `util_config.py`. This PR is a workaround to disable the `mypy` errors. A fix in Matplotlib is being considered in matplotlib/matplotlib#28518.

Workaround for plt.subplots return types

---

.github/workflows/test.yml
pyproject.toml

Bump minimum supported NumPy to 1.23, not quite following [SPEC0](https://scientific-python.org/specs/spec-0000/) but heading in that direction.

Bump minimum supported numpy to 1.23

---

.github/workflows/test.yml
pyproject.toml

NumPy are building nightly wheels for PyPy 3.10 so here do the same and add a CI run.

Test and build wheels on PyPy 3.10

---

pyproject.toml

CI on Windows is failing with access violations when using Matplotlib 3.9.1 for testing, but with 3.9.0 it seems to be OK. This PR therefore pins Matplotlib to < 3.9.1 on Windows to confirm this.

Pin matplotlib < 3.9.1 on Windows

---

.github/workflows/build_wheels.yml
pyproject.toml

Related to #407.
FYI running `cibuildwheel` for `manylinux` locally successully built a wheel for free-threaded 3.13.

Build wheels for the 3.13 free-threaded build of CPython

---

pyproject.toml

Do not build free-threaded wheels on Windows, see #411.

Do not build free-threaded wheels on Windows

---

.github/workflows/test.yml
pyproject.toml

As part of the ongoing issue of crashes caused by matplotlib 3.9.1 (matplotlib/matplotlib#28551) here trying some experiments:
1. Re-enable Windows tests against Matplotlib 3.9.1, expecting these to fail.
2. Re-enable image tests when using Matplotlib nightly wheels. Up until yesterday these failed for me locally, today they pass so need to try to reproduce in GHA.

Use image tests on windows with mpl nightly wheels

---

pyproject.toml
src/meson.build

Use `delvewheel` when building wheels on Windows, as requested in matplotlib/matplotlib#28551. Also reinstated the MSCV `std::mutex` workaround of #391 as without it the test of the 64-bit wheel fails, presumably because we're packaging an 'old' version of the MSVC DLL.

Use delvewheel when building windows wheels

---

pyproject.toml
src/meson.build

Reverting (well, commenting out really) PR #414 which added use of `delvewheel` when building Windows wheels and sets `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR`. This simple use of `delvewheel` is not correct, there is a more complicated set of build options for Matplotlib on Windows being tried out. I want to go back to creating nightly wheels as they were a month ago, to see if they are compatible with the new Matplotlib options.

Revert PR #414, use of delvewheel

---

build_requirements.txt
pyproject.toml

Avoid use of pybind11 2.13.3 which introduced erroneous quoting of compiler arguments on Windows such as:
```
"'-IC:\hostedtoolcache\windows\Python\3.12.4\x64\Include'"
```
Ref https://github.com/pybind/pybind11/issues/5300#issuecomment-2287698500.

Avoid use of pybind11 2.13.3 due to Windows quoting bug

---

.github/workflows/test.yml

With the release of Python 3.13 wheels by numpy and upstream projects used for testing (matplotlib, pillow) the testing of python 3.13 can be done in the standard manner including image comparison tests. This also applies to the 3.13 free-threading CI run.

Test on Python 3.13 in standard manner

---

.github/workflows/test_own_nightlies.yml

Add new CI workflow to test own nightly wheels as mentioned in #424. Test against both released and nightly wheels of test dependencies, and run the full test suite with image comparison tests. Workflow runs once per week a few hours after nightly wheels are uploaded, and also on demand via workflow dispatch. Only really needs to test on Windows, but I've included Linux and macOS as well.

New CI workflow to test own nightly wheels

---

.github/workflows/build_wheels.yml
pyproject.toml

With the release of NumPy 2.1.0 which includes PyPy 3.10 and CPython 3.13 and 3.13t wheels we no longer need to install NumPy nightlies to test against when building ContourPy wheels.
Also moved `CIBW_FREE_THREADED_SUPPORT` env var from cibuildwheel github action to `pyproject.toml` setting.

Don't need to use NumPy nightlies when building wheels

---

lib/contourpy/util/meson.build
pyproject.toml
src/meson.build

Statically link C++ runtime on Windows when building wheels.
Fixes #424.

Statically link C++ runtime on Windows

---

README.md
README_simple.md
docs/conf.py
docs/installation.rst

Remove download numbers for conda packages as Anaconda haven't made the package data available for the past 2 months. Also remove instructions for installing from Anaconda default channel as that isn't kept up to date either.

Remove download numbers for conda packages

---

.cirrus.yml
.github/workflows/build_wheels.yml
.github/workflows/test.yml
.readthedocs.yaml
pyproject.toml

Bump default python version in CI to 3.12. Also removed the cirrus macos arm64 run as that has been reliably working in github actions for a while now.

Bump default python version in CI to 3.12

---

docs/conf.py
docs/installation.rst
docs/quickstart.rst
docs/usage.rst
docs/user_guide/calculate/index.rst
docs/user_guide/manipulate/convert.rst
docs/user_guide/manipulate/dechunk.rst
docs/user_guide/manipulate/index.rst
lib/contourpy/convert.py
lib/contourpy/dechunk.py
lib/contourpy/util/renderer.py
src/wrap.cpp

Add documentation for `multi_lines` and `multi_filled`, including for renderers and the various `convert_*` and `dechunk_*` possibilities. Also documented availability of nightly wheels.

Docs for multi_lines and multi_filled

---

.github/workflows/test.yml
pyproject.toml

Drop support for Python 3.9 following a delayed [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table).

Drop support for Python 3.9

---

lib/contourpy/util/bokeh_renderer.py
tests/test_bokeh_renderer.py

Fixes test failures caused by upgrade to Bokeh 3.6.0, and improved the SVG test at the same time.

Update to bokeh 3.6.0

---

.github/workflows/build_wheels.yml

* scientific-python/upload-nightly-action v0.6.1 fixes a breaking bug in v0.6.0.
- c.f. https://github.com/scientific-python/upload-nightly-action/releases/tag/0.6.1
c.f. https://github.com/scientific-python/upload-nightly-action/issues/106

ci: Bump scientific-python/upload-nightly-action from 0.6.0 to 0.6.1

---

.github/workflows/test.yml

After the official release of CPython 3.13 can tidy up how it is referenced in CI.

Tidy up python 3.13 CI

---

pyproject.toml

Now that Python 3.13 free-threaded Windows wheels are available for NumPy (numpy/numpy#26157) we can build and test ContourPy nightly wheels for the same to help downstream libraries such as Matplotlib do the same (matplotlib/matplotlib#28819).

Build Python 3.13t wheels on Windows

---

build_requirements.txt
pyproject.toml

Update minimum pybind11 to 2.13.2 as use of 2.13.1 can cause mutex problems in free-threaded builds. This is not an issue with the latest contourpy release 1.3.0 (the only release to support python 3.13) was built using pybind11 2.13.5 on PyPI and 2.13.6 on conda-forge, confirmed using:
```bash
python -c "import contourpy.util as u; print(u.build_config()['pybind11_version'])"
```

Update minimum pybind11 to 2.13.2

---

lib/contourpy/util/meson.build

`meson-python` is removing `__version__` so change reading of this for `build_config` to use the recommended `importlib.metadata.version('meson-python')` instead. See mesonbuild/meson-python#691.
Tested locally using `meson-python` `main` branch (commit `9faca831`) and the build fails before this fix and passes afterwards with
```bash
$ python -c "import contourpy.util as cu; print(cu.build_config()['mesonpy_version'])"
0.18.0.dev0
```

Read meson-python in recommended way

---

pyproject.toml

There are `mypy` CI failures when using `numpy 2.2.0`. Some are genuine, some are bugs that will be fixed in the next numpy release e.g. numpy/numpy#27967. Temporarily pin `numpy` used for type checking until then.

Pin numpy<2.2 when type checking using mypy

---

.github/workflows/build_wheels.yml
.github/workflows/test.yml
.github/workflows/test_own_nightlies.yml

Linux ARM github runners are now available https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/. Here adding a single linux arm CI test run, and more importantly switching the `aarch64` wheel builds across to use an arm runner so that they are no longer emulated.

Use ubuntu-24.04-arm runners

---

.github/workflows/test.yml

Coverage CI runs have started failing with some errors reported that are neither correct nor important. Here ignoring those errors.

Ignore some coverage errors

---

.github/workflows/build_wheels.yml
.github/workflows/test.yml

Temporary workaround for seg faults occurring in CI when emulating `ppc64le` or `s390x` using qemu. Workaround from pypa/cibuildwheel#2256.

Temporary workaround for qemu segfault

---

.github/workflows/test.yml

Test PyPy 3.10 on all 3 major OSes rather than just ubuntu, and obtain `numpy` packages from PyPI rather than scientific python nightly wheels.

Test PyPy 3.10 on all 3 major OSes

---

.github/workflows/test.yml

Remove use of deadsnakes as the standard `setup-python` actions supports free-threading python.

Remove use of deadsnakes for free-threading python

---

lib/contourpy/util/bokeh_renderer.py
pyproject.toml

Fix type annotations for bokeh >= 3.7, closes #466.

Fix type annotations for bokeh >= 3.7

---

pyproject.toml

Following #476, need to ensure that building wheels for Windows ARM uses numpy nightly wheels (they are not on PyPI yet) and do not build for python 3.10.

Fix building windows arm wheels

---

.github/workflows/test.yml
pyproject.toml

Bump minimum supported Python to 3.11 and NumPy to 1.25 following delayed [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table).

Bump minimum supported Python to 3.11

---

.github/workflows/test_own_nightlies.yml

Disable nightly wheels test on Windows on ARM, waiting for Matplotlib wheels (matplotlib/matplotlib#28554).

Disable nightly wheels test on Windows on ARM

---

.github/workflows/test.yml
lib/contourpy/array.py
pyproject.toml

Previously pinning python 3.13 CI runs to 3.13.3 as there was a problem with 3.13.4 on Windows. This is no longer necessary as 3.13.5 is reliably available in github runners.

Remove 3.13.3 pin

---

.github/workflows/test.yml

Reinstate image tests for python 3.14. Need to install kiwisolver from source.

Reinstate image tests for python 3.14
